apache/mynewt-nimble

- porting/common/include/os/os_fault.h
- porting/common/src/os/os_mempool.c
- Support pointer alignment on 64-bit architectures.
- C++ extern "C" typo.
> [osal] Minor fixes to the os abstraction porting layer.

- nimble/host/services/bas/include/services/bas/ble_svc_bas.h
- nimble/host/services/bas/pkg.yml
- nimble/host/services/bas/src/ble_svc_bas.c
- nimble/host/services/bas/syscfg.yml
See: https://github.com/apache/mynewt-core/pull/904
> ble service: Battery Service

- nimble/controller/include/controller/ble_ll_conn.h
- nimble/controller/include/controller/ble_ll_ctrl.h
- nimble/controller/src/ble_ll_adv.c
- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_conn_hci.c
- nimble/controller/src/ble_ll_conn_priv.h
- nimble/controller/src/ble_ll_ctrl.c
- nimble/controller/src/ble_ll_hci.c
This PR fixes couple of bugs found during LL testing.
> nimble/ll: Portion of fixes for the nimble controller.

- nimble/controller/src/ble_ll_resolv.c
With this patch, controller will accept resolving timeout even resolving
is not yet enabled.
> nimble/ll: Fix HCI Set Resolving Timeout

- nimble/host/services/dis/include/services/dis/ble_svc_dis.h
- nimble/host/services/dis/pkg.yml
- nimble/host/services/dis/src/ble_svc_dis.c
- nimble/host/services/dis/syscfg.yml
See: https://github.com/apache/mynewt-core/pull/901
> ble service: Device Information Service

- nimble/controller/include/controller/ble_ll.h
- nimble/controller/src/ble_ll.c
- nimble/controller/src/ble_ll_adv.c
- nimble/controller/src/ble_ll_hci.c
Fixes for handling legacy vs extended advertising commands and LE Set Random Address.
> nimble/ll: HCI fixes

- nimble/drivers/nrf52/src/ble_phy.c
nRF52 radio can ramp-up from idle state so it can be either disabled or
idle (for whatever reason - it happens sometimes) when starting RX.
Similar problem was already fixed on nRF51 by forcing radio disable
since that radio can ramp-up only from disabled state.
> nimble/phy: Allow idle state when starting RX

- nimble/host/services/ans/src/ble_svc_ans.c
- nimble/host/services/bas/src/ble_svc_bas.c
- nimble/host/services/ias/pkg.yml
> fix spelling errors

- nimble/host/services/ans/include/services/ans/ble_svc_ans.h
- nimble/host/services/bas/include/services/bas/ble_svc_bas.h
minute change: correction of spellings in comments.
> Correct spelling in comment

- nimble/controller/src/ble_ll_adv.c
- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_conn_hci.c
- nimble/controller/src/ble_ll_conn_priv.h
- nimble/controller/src/ble_ll_hci.c
- nimble/host/src/ble_gap.c
Few fixes for issues found during qualification process.
> Fixes for connection creation events handling

- nimble/controller/src/ble_ll_adv.c
This fix applies only to advertising extensions.
> nimble/ll: Fix for setting address type for directed advertising

- nimble/controller/src/ble_ll_scan.c
mempool shouldn't be initialized on HCI Reset as it may affect other
pools. Instead initialize it only on init and cleanup on HCI Reset.
> nimble/ll: Fix scanner init on HCI Reset

- nimble/controller/src/ble_ll_adv.c
- nimble/host/include/host/ble_gap.h
- nimble/host/src/ble_gap.c
- nimble/syscfg.yml
This fixes few issues with extended advertising found thanks to issue #44. Most of them are related to handling `duration` parameter for advertising set.
> Multiple fixes to extended advertising

- nimble/controller/src/ble_ll_adv.c
For legacy advertising any interval between 0x0020 and 0x4000 is valid
as long as min interval is not greater than max interval.
For extended advertising any interval between 0x000020 and 0xffffff
is valid as long as min interval is not greater than max interval.
If intervals provided are outside of value allowed by specificication
then Invalid Parmeters error is returned.
If the advertising interval range provided by the Host is valid but
outside the advertising interval range supported by the Controller,
then the Controller shall return the Unsupported Feature or Parameter
Value (0x11) error code. Since for now we support only intervals
in legacy range we use this code in that case.
This was affecting TP/DDI/BI-02-C qualification test case.
> nimble/ll: Fix advertising interval validation

- nimble/host/src/ble_gap.c
This makes GAP code to trim mbuf chain with adv data while consuming
it but before sending HCI commands. Thanks to this is is possible
to use MSYS pool from application for data which is later reused by
controller resulting is smaller pool being needed.
> nimble/gap: Optimise setting data with extended advertising

- nimble/transport/socket/src/ble_hci_socket.c
- Update hci_sock transport to use NPL os abstractions.
- Fix hci_sock to properly take down HCI interface before configuring socket.
> [hci_sock] Update hci socket transport to use NPL.

- CODING_STANDARDS.md
- LICENSE
- NOTICE
- README.md
- RELEASE_NOTES.md
This includes coding style, license and README.
> Add some initial documentation

- nimble/host/mesh/src/glue.c
> porting: Fixes for compilation errors

- nimble/transport/uart/src/ble_hci_uart.c
This adds prioritization of events received. This allows to allocate
membuf for LE Advertising events from low prio mempool.
This patch is needed for host to work in high poluted environment,
where advertisements received may block the host from receiving
other more important events from controller.
> transport: uart: Prioritize events

- nimble/drivers/nrf52/src/ble_phy.c
wfr is set using CC[0] or CC[2] as reference, but since CPU may be
halted for a brief moment between timer capture and wfr calculations it
may happen that TIMER0 already counted past calculated value and compare
will not occur as expected. This can leave radio stuck in RX state, e.g.
in case we are advertising and waiting for scan/connect req after TX.
To fix this we'll just check if wfr is set past current TIMER0 counter
value and if so, we'll disable radio manually as if wfr fired.
This is similar to 06cfc0b0 but happens for reverse transition.
> nimble/phy: Fix late wfr setup

- nimble/host/mesh/src/access.c
Previously we only checked if any of the models within the element have
the destination address in their subscription list. After that check the
specific model that the message was addressed to was not verified to have that
address in it's subscription list. This patch fixes this problem.
> [RFC] mesh: Check if a model is subscribed to the destination address

- nimble/host/include/host/ble_gatt.h
nimble/host: Fix ble_gattc_indicate_custom comment
> nimble/host: Fix ble_gattc_indicate_custom comment

- nimble/controller/src/ble_ll_dtm.c
No need to assert, just set for reschedule and continue.
> nimble/ll/dtm: Reschedule late TX PDU

- nimble/controller/include/controller/ble_ll.h
- nimble/controller/src/ble_ll.c
- nimble/controller/src/ble_ll_dtm.c
Few improvements so we do not assert in cases which can happen during DTM.
> DTM: few improvements

- nimble/host/include/host/ble_gap.h
- nimble/host/src/ble_gap.c
This may be useful in some cases.
> host/gap: Add connection find by address API

- nimble/host/src/ble_att_clt.c
- nimble/host/src/ble_att_svr.c
- nimble/host/src/ble_gattc.c
- nimble/host/src/ble_uuid.c
- nimble/host/src/ble_uuid_priv.h
- nimble/host/test/src/ble_hs_test_util.c
This is more generic approach for issue described in https://github.com/apache/mynewt-nimble/pull/193.
> nimble/host: Fixes for UUID handling

- nimble/controller/src/ble_ll_scan.c
- nimble/controller/src/ble_ll_sched.c
- nimble/host/mesh/src/prov.c
These are minor patches created while working on other stuff want to push it now before actual PR with more important fixes.
> nimble: Minor cleaning patches.

- nimble/host/mesh/src/adv.h
- nimble/host/mesh/src/testing.c
- porting/npl/linux/include/console/console.h
- porting/npl/linux/src/os_callout.c
- porting/npl/linux/src/os_eventq.cc
- porting/npl/linux/src/os_time.c
- porting/npl/linux/src/wqueue.h
Following commits includes:
1. Fixes for build errors which I encountered while building BLE Mesh app on Linux platform
2. Fixes for functionality failure while running the BLE Mesh app on Linux platform
> [porting][linux] Add support for BLE Mesh app on linux platform

- nimble/controller/src/ble_ll_ctrl.c
The code was not correctly handling the case where a slave receives
a connection update where the current connection event counter is
equal to the instant in the connection update PDU. This is a valid
case (as per spec errata). With this fix the controller should
correctly handle this case.
> net/nimble/controller: Slave connection update fix

- nimble/controller/src/ble_ll_conn.c
Without this patch we will get assert on legacy connect
> nimble/ll: Fix regression on legacy connect

- nimble/controller/src/ble_ll_ctrl.c
We should response with LL_UNKNOWN_RSP
This should fix LL/PAC/MAS/BV-01
Note: Patch looks big but in fact it is not. Most of it is indentation change since  ` if (connsm->conn_role == BLE_LL_CONN_ROLE_SLAVE) {`  has been removed as it is not needed anymore.
> nimble/ll: Fix handling LL_PHY_UPDATE_IND as a master

- nimble/controller/include/controller/ble_ll_conn.h
- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_conn_hci.c
See commit messages for details.
> nimble/ll: Qualification fixes related to privacy and directed advertising

- nimble/controller/include/controller/ble_ll_scan.h
- nimble/controller/src/ble_ll_scan.c
Solving https://github.com/apache/mynewt-nimble/issues/213
> nimble/ll: Do not send SCAN REQ to already scanned ext advertising

- apps/blehr/src/main.c
Use conn_handle in ble_gattc_notify_custom() instead o incorrect notify_state
> blehr: Fix state notifications

- nimble/controller/src/ble_ll_adv.c
- nimble/host/src/ble_gap.c
This PR make sure advertising is stopped while data are updating.
> nimble/ll: Fix updating adv and scan response data while advertising

- nimble/controller/src/ble_ll_adv.c
This PR brings two changes:
1. It makes sure TargetA is added only to scannable AUX_ADV_IND
and not later to AUX_SCAN_RSP and chains.
2. Add support for anonymous advertising
> nimble/ll: Improvements for extended advertising

- nimble/controller/src/ble_ll_adv.c
We always use the same channel on secondary phy for all auxes in chain.
This is not stritcly incorrect, but we should better randomize channel
for each aux in chain which is what this patch does.
> nimble/ll: Fix randomizing channel on sec phy

- apps/btshell/src/btshell.h
- apps/btshell/src/cmd.c
- apps/btshell/src/main.c
Add stop to ongoing test-tx and console printouts to monitor ongoing test.
> btshell: Improve test-tx command

- nimble/controller/src/ble_ll_ctrl.c
If slave requested symmetric PHY on PHY change we should either change
both directions to the same PHY or leave both unchanged.
This fixes LL/CON/MAS/BV-117C.
> nimble/ll: Fix PHY update on symmetric PHY from slave

- nimble/host/src/ble_sm.c
> nimble/host: Fix ble_sm_tx called without a lock

- porting/nimble/src/hal_timer.c
Addressing finding pointed out in #365
By hard-coding the interrupt handling, the `hal_timer` implementation circumvents the npl abstraction, ignoring any port-specific implementations of `OS_ENTER/EXIT_CRITICAL`. See #365 and #366
This PR make `hal_timer` simply use the port specific macros for handling its critical sections. As I am not too familiar with any other implementations than the RIOT port, I can't really judge the possible side-effects of this change, so please review and test carefully :-)
> porting/hal_timer: use OS_[ENTER/EXIT]_CRITICAL()

- nimble/controller/src/ble_ll_adv.c
Since it can be changed in interrupt and ll task context, move it to
critical section.
> nimble/ll: Protect advsm->flags

- apps/btshell/src/btshell.h
- apps/btshell/src/cmd.c
- apps/btshell/src/main.c
- nimble/host/include/host/ble_gap.h
- nimble/host/src/ble_gap.c
- nimble/host/src/ble_sm.c
- nimble/host/src/ble_sm_priv.h
- nimble/host/src/ble_sm_sc.c
The key size was not properly persisted across connections.
Fixes #403.
> nimble: Fix handling and storing encryption key size

- nimble/host/src/ble_hs_hci_evt.c
Prior to PR: The code assumed that a transmission could stall for only one reason: the controller cannot accommodate any more ACL data packets.  When the host received a num-complered-packets event, it would only try to unstall each connection if all the controller's data buffers were previously used.
It turns out there is a second way that a host connection can stall: mbuf exhaustion.  If the host is unable to fragment an outgoing L2CAP packet into ACL data packets due to a lack of mbufs, the transmission stalls.
This PR causes the host to wake up its connections every time it receives a num-completed-packets event.  It does this even if the controller still had capacity for more ACL data packets.  If a host connection is stalled due to mbuf exhaustion, the controller will only send the …
> host: Always wake tx queues on rx of num-cmp-pkts

- apps/bleprph/pkg.yml
- apps/bleprph/src/main.c
- apps/bleprph/syscfg.yml
This can also include firmware (image) version.
> apps/bleprps: Add DIS to bleprph

- apps/btshell/src/cmd.c
- nimble/host/include/host/ble_gap.h
- nimble/host/src/ble_gap.c
- nimble/host/src/ble_hs_periodic_disc.c
- nimble/host/src/ble_hs_stop.c
This PR moves terminating all periodic sync on Host shutdown (bl_hs_stop()) to better place.
> nimble/host: Couple of improvements around periodic adv 

- apps/bttester/src/gap.c
This path caused errors in CI.
> apps/bttester: Fix include path

- nimble/host/src/ble_hs_hci_evt.c
Fix periodic advertising issue as data copied outside the structure
> nimble/hci : Fix periodic advertising report issue

- nimble/drivers/nrf52/src/ble_phy.c
PHY start time was incorrectly set on late start because COUNTER
register was used instead of proper cputime. This caused start time to
be set to 24-bit value which became incorrect as soon as cputime value
exceeded 0xffffff.
> nimble/phy: Fix start time on late RX

- nimble/host/mesh/src/proxy.c
Mesh Profile 1.0 Section 6.6:
"The timeout for the SAR transfer is 20 seconds. When the timeout expires,
the Proxy Server shall disconnect."
This allows passing MESH/SR/PROX/BV-05-C.
> nimble/mesh: Fix missing SAR timeout in Proxy Server

- nimble/host/services/dis/include/services/dis/ble_svc_dis.h
- nimble/host/services/dis/src/ble_svc_dis.c
- nimble/host/services/dis/syscfg.yml
This PR adds the System ID characteristic to DIS. 
Also fixes some indentation inconsistencies.
> Adding System ID characteristic to DIS.

- apps/bttester/src/gap.c
- apps/bttester/syscfg.yml
This is needed to pass TP/BROB/BCST/BV-04-C.
> apps/bttester: Add option to use NRPA

- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_conn_hci.c
This patch puts g_ble_ll_conn_create_sm into critical section.
> nimble/ll: Fix cancel connection creation

- nimble/controller/include/controller/ble_ll_scan.h
- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_scan.c
- nimble/controller/src/ble_ll_sched.c
This PR simplifies usage of aux_data ref counter.
> nimble/ll: Fix aux_data ref counter

- nimble/host/src/ble_sm.c
When host is configure for SC only mode, make sure to reject pairing
when remote wants Legacy pairing.
This fixes GAP/SEC/SEM/BV-23-C and GAP/SEC/SEM/BV-24-C
> nimble/gap: Fix for checking sc only mode

- nimble/controller/src/ble_ll_conn.c
Regression after
e46fdc90 nimble/ll: Fix peer address check with privacy
Regression prevented to connect to unknown device which uses RPA
> nimble/ll: Fix regression on connection to RPA

- nimble/controller/src/ble_ll_scan.c
This patch refactors duplicates filtering to make it more robust by
auto-expiring entries, removes limitation of 255 entries in cache and
properly handles extended advertising reports for multiple sets and
anonymous devices.
Instead of a static array we use mempool of dup_entries which are linked
to create a queue where most recently found device is placed on top.
This allows to simply remove least recently found devices from queue
when list capacity is reached and thus keep filtering new devices.
Legacy advertising devices are simply matched by address thus each
device has single entry in the queue.
Extended advertising devices are matched by address and SID thus each
device can have multiple entries in queue (for each SID).
> nimble/ll: Refactor duplicates filtering

- nimble/host/include/host/ble_gap.h
- nimble/host/src/ble_gap.c
- nimble/host/src/ble_gap_priv.h
- nimble/host/src/ble_hs_hci_evt.c
- nimble/include/nimble/hci_common.h
> Improvements to HCI handling in host

- nimble/host/mesh/src/prov.c
This patch contains a few proposed patches from Mynewt that
were backported to Zephyr and since there were other differences
in this file I decided to sync it in one commit.
In sync with this PR:
https://github.com/zephyrproject-rtos/zephyr/pull/17117
> nimble/mesh: Sync provisioning code with Zephyr

- nimble/controller/src/ble_ll_conn.c
Core Specification Vol 6, Part B, Section 6.4:
"The Link Layer should not set the InitA field to the same
value as the TargetA field in the received advertising PDU."
> nimble/ll: Use a different RPA when initiating Directed Connection

- nimble/controller/include/controller/ble_ll_scan.h
- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_scan.c
- nimble/controller/src/ble_ll_sched.c
> nimble/ll: Fixes and cleanups after refactor of aux_data ref cnt

- nimble/controller/src/ble_ll_conn.c
It looks like there is a race when closing connection with different
paths. It can lead to situation that Nimble tries to close connsm which is
already in IDLE, which leads to crash when removing connsm from
g_ble_ll_conn_active_list which does not contain connsm.
This patch adds workaround and plus assert and stats which should help
to understand the root cause
> nimble/ll: Workaround and traces for the possible race scenario

- nimble/drivers/nrf51/src/ble_phy.c
- nimble/drivers/nrf52/src/ble_phy.c
Optimized ble_phy_rxpdu_copy (f19002e) can overwrite header of adjacent
block at specific payload lengths.
This happens if length of data that should be copied to last mbuf in
chain is less than 4 bytes of data. In such case the last but one mbuf
is already full when remaining data are appended to it beyond its data
buffer effectively overwriting adjacent buffer.
We should always check if there is enough space in current mbuf to copy
data. If not, we just advance to next mbuf in chain. Even in such case
there will be free mbuf to store remaining few bytes of data as this is
guaranteed by ble_ll_rxpdu_alloc.
> nimble/phy: Fix memblock overwrite

- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_dtm.c
- nimble/controller/src/ble_ll_scan.c
- nimble/drivers/nrf51/src/ble_phy.c
- nimble/drivers/nrf52/src/ble_phy.c
- nimble/host/mesh/src/proxy.c
Few fixes for upcoming 1.2-rc2
> Fixes for 1.2-rc2

- nimble/controller/src/ble_ll_scan.c
With this patch we move restarting RX on wfr while scanning to interrupt
context instead of LL context.
It is because we want to restart RX as fast as possible while scanning.
Also previous ble_phy_restart_rx call in LL context during
interrupts enabled was incorrect.
> nimble/ll: Fix restarting rx on wfr while scanning

- apps/blecsc/src/main.c
- apps/bttester/src/gatt.c
- apps/bttester/src/l2cap.c
- nimble/controller/include/controller/ble_ll.h
- nimble/host/test/src/ble_hs_conn_test.c
- nimble/transport/uart/src/ble_hci_uart.c
- porting/npl/linux/test/test_npl_callout.c
- porting/npl/linux/test/test_npl_eventq.c
- porting/npl/linux/test/test_npl_mempool.c
- porting/npl/linux/test/test_npl_task.c
Fix warnings when compiling with '-Wstrict-prototypes'
> fix -Wstrict-prototypes issues

- porting/nimble/include/os/util.h
This might be useful for portings.
> nimble/porting: Add util.h

- nimble/host/mesh/src/prov.c
- nimble/host/src/ble_sm_alg.c
Minor fix in `ble_sm_alg.c` and `prov.c`
> Host: Remove unnecessary inclusion of headers

- apps/bttester/src/bttester.c
- apps/bttester/src/bttester.h
- apps/bttester/src/bttester_pipe.h
- apps/bttester/src/gap.c
- apps/bttester/src/gatt.c
- apps/bttester/src/mesh.c
- apps/bttester/src/uart_pipe.c
- apps/bttester/syscfg.yml
Various improvements to the application needed to work with latest changes in [autopts](https://github.com/intel/auto-pts) and [BTPTesterCore](https://github.com/JuulLabs-OSS/BTPTesterCore).
> apps/bttester: Updates and improvements

- nimble/host/pts/pts-gap.txt
- nimble/host/pts/pts-gatt.txt
Upgrade instructions and results test cases in pts.
> Upgrade test instructions

- apps/btshell/src/cmd.c
Nimbles does it for us, let's remove it from test app.
> btshell: Remove tracking adv instances

- nimble/host/src/ble_hs_flow.c
- nimble/include/nimble/hci_common.h
Thiscode was not updated to use packed structs.
> nimble/host: Fix controller to host flow control

- nimble/controller/src/ble_ll_adv.c
Some parameters were not ignored correctly.
> nimble/ll: Fix Extended Advertising Set Parameters parsing

- nimble/controller/src/ble_ll_conn.c
If WL is disabled and host provided peer RPA in LE Create Connection
peer address and adress type needs to be updated. Otheerwise host
will receive LE Enhanced Connection event with invalid ID address
and ID address type.
This was affecting LL/CON/MAS/BV-102-C qualification test case.
> nimble/ll: Fix reporting peer ID addr without WL enabled

- nimble/controller/src/ble_ll_scan.c
We shoould not send reports for SCAN_RSP that has AdvA which is not
ours.
This fixes LL/DDI/SCN/BI-03.
> nimble/ll: Ignore SCAN_RSP not addresses to us

- nimble/controller/src/ble_ll_scan.c
- nimble/controller/src/ble_ll_sched.c
another set of fixes for rfclk handling. I'll probably consider refactoring this code in one of next PRs since it's apparently quite easy to get this thing out of sync...
> RFCLK handling fixes

- nimble/controller/src/ble_ll_ctrl.c
This leaves periodic sync code PHY unrelated. If none is enabled
code will ve removed by linker.
> nimble/ll: Fix build with periodic sync enabled and PHY disabled

- nimble/drivers/nrf52/src/ble_phy.c
AAR was configured to resolve address after calling ble_ll_isr_start
which means that more bits were received in the meantime. This means
that it was possible that last bit of AdvA was already received when we
configure BCC trigger thus AAR was never triggered. Now we configure
AAR immediately so it's unlikely that complete AdvA can be received
during this time.
Also, we only want AAR to do its job for random addresses so just skip
it if TxAdd==0.
> nimble/phy: Optimize address resolution on nRF

- nimble/controller/src/ble_ll_sync.c
If calculated max_skip interval is larger than sync timeout we adjust it
to be the same as timeout. However, this means we have only single event
to scan properly or sync will be lost.
To avoid this, let's adjust max_skip by an extra 6 events (the same as
used when syncing) so we will have at least 6 events to scan before sync
is lost.
> nimble/ll: Adjust max_skip to include some error margin

- nimble/controller/src/ble_ll_sync.c
Don't set anchor point in the middle of expected window for first
packet. Now we set anchor to calculated point in time and adjust
WFR with window widenning (and offset if synchronizing).
> nimble/ll: Fix setting anchor point and WFR for sync PDUs

- nimble/host/src/ble_hs_hci.c
NOP can be sent as Command Complete or Command Status. Those events
don't have opcode field in same place so old code was not checking
proper bytes. It looks like this never worked for Command Status case.
> nimble/host: Fix checking for NOP in ble_hs_hci_rx_evt

- nimble/controller/src/ble_ll_ctrl.c
This fixes PHY switch in case slave tries to change from asymmetric to
symmetric PHY and the target PHY is one of currently used PHYs. The
issue is because we first calculate PHY change in both directions and
only then check if slave requested symmetric PHY. However, since either
m_to_s or s_to_m are already set to 0 (due to no change required), the
subseqent checks assume we should not change PHY in either direction.
The current behavior is technically correct, since master is always
allowed to leave PHY in both directions unchanged, but it's just dumb
since we should make a change assuming our PHY preference allows it.
To fix this we basically skip PHY calculation if we determined that
slave requested symmetric PHY and we can apply it in both directions.
If requested symmetric PHY …
> nimble/ll: Fix PHY change on slave request

- nimble/controller/src/ble_ll_adv.c
If advertising event is interleaved by current periodic event offset
was calculated from that event, and not future event. This resulted
in sending SyncInfo with offset=0 which was causing random failures
on LL/DDI/ADV/BV-56-C qualification test.
> nimble/ll: Fix offset calculation in SyncInfo

- nimble/controller/src/ble_ll_dtm.c
1st DTM packet does not take scheduler offset into account so actual
start time is before RFMGMT enable time and this apparantly makes things
go out of sync.
This also makes scheduling more intuitive as we keep track of TX start
time separately from scheduler item (as in advertising) so scheduler
start_time can be updated with scheduler offset in-place (as it is
already done) without risk that we use invalid value somewhere.
> nimble/ll: Fix DTM TX scheduling

- nimble/host/src/ble_hs_id.c
As per spec v5.1, Vol 6, part B, section 1.3.2.1, random part of of static address should follow:
• At least one bit of the random part of the address shall be 0
• At least one bit of the random part of the address shall be 1  
In my previous PR: [PR!435](https://github.com/apache/mynewt-nimble/pull/435), I had checked all bits of random address but only random part should have been addressed.
> nimble/host: Fix check for valid static random address

- .style_ignored_dirs
- .travis.yml
- uncrustify.cfg
Enable style checking (and add requires files).
> Add CI style checking

- nimble/host/test/src/ble_l2cap_test.c
struct ble_l2cap_sig_credit_base_connect_{req,rsp} are variable length
packets and we must provide storage for cids. This fix test failure on
MacOS.
> nimble/test: Fix stack corruption in ble_l2cap_test_coc_connect_multi

- .rat-excludes
- NOTICE
- README.md
This fixes dates, license headers and NOTICE.
> Fixes for 1.3 release

- apps/scanner/pkg.yml
- apps/scanner/src/main.c
Basic scanner app discovering advertising devices and printing advertising report data to serial port.
> apps: scanner added

- apps/central/pkg.yml
- apps/central/src/main.c
Added central application which presents how to connect to peripheral.
> Apps: central added

- apps/README.md
Added readme describing sample applications
> Apps: readme added

- nimble/host/src/ble_l2cap_coc.c
I also stumbled upon some more non-thread-safe lines in the `ble_l2cap_coc` code while debugging erratic node behavior in the context of #865.
Mainly the operation of setting `tx->sdu = sdu_tx;` in `ble_l2cap_coc_send()`, called by any user thread, could theoretically be interrupted from the NimBLE host thread and be overwritten before `ble_l2cap_coc_send()` returns. This is now prevented by doing this assignment inside a locked host. 
To further prevent any context switch to interfere, I moved both calls to `ble_l2cap_event_coc_unstalled()` inside a locked host environment. With this it is guaranteed, that any changes to the sending state (possible by `ble_l2cap_coc_send()` or `ble_l2cap_coc_le_credits_update()`) are always complete before any interruption can occur.
I have been …
> host/l2cap_coc: harden TX thread safety

- nimble/controller/src/ble_ll.c
This one took me a long time to find and it had devastating effects: the STDLIBs pseudo random number generator was not properly seeded by the controller. As the comment in the code, wisely starting with `XXX`, perfectly stated: `This really doesn't belong here, as the address probably has not been set yet.`. At least when using the NimBLE controller with RIOT, that comment is absolutely true... So when running multiple nodes, all use the same seed making their random number identical.
When running my deployment using 15 nRF52xxx nodes in a multi-hop network, I observed the following faulty behaviors:
- application data was duplicated and received on nodes that did not have a direct connection to nodes sending this data
- L2CAP COC flow control getting out of sync: RX or TX credit counts …
> controller: properly seed srand() during initialization

- nimble/host/mesh/src/friend.c
- nimble/host/mesh/src/net.h
According MESH/NODE/FRND/FN/BV-20-C should add another
Friend Update.
This is port of Zephyr patch:
commit 355bdf5cd95d9f8bf11fc0f00fb1bcb151ff5cab
> mesh/friend.c - Fixes Friend Add Another Update

- nimble/transport/dialog_cmac/cmac_driver/include/cmac_driver/cmac_shared.h
- nimble/transport/dialog_cmac/cmac_driver/src/cmac_host.c
This adds few updates for CMAC:
- add locking for shared data access
- optimize wakeup for LP clock frequency change
- prepare for proper RF recalibration request
> Updates for CMAC

- nimble/drivers/dialog_cmac/src/ble_phy.c
There is a very small window between setting timer comparator and
configuring field_1 where frame_start event can happen due to match
on that timer. To prevent this from generating a fatal error, let's
disable corresponding error before setting comparator and check if
frame_start event already happened after frame_1 is configured. If
it did happen, assume we did not configure frame_1 on time and do
tx_late.
> nimble/phy: Improve tx_late handling

- nimble/drivers/dialog_cmac/src/ble_phy.c
Disabling some errors temporarily to avoid tx_late does not work
properly because those errors are not reset when BS is reset and we
may still have CMAC error after those errors are enabled.
To make things work let's just keep all relevant errors disabled and
ignore them since we can use exceptions status to detect tx_late pretty
consistently.
> nimble/phy: Fix tx_late handling

- porting/examples/dummy/Makefile
- porting/examples/linux/Makefile
- porting/examples/linux_blemesh/Makefile
this fixes https://github.com/apache/mynewt-nimble/issues/903
> porting: fix typo in CROSS_COMPILE

- nimble/controller/src/ble_ll_scan.c
This fixes assert in ble_ll_scan_aux_data_unref() during scan under
heavy load. This happens when we scanned an aux with auxptr, but we
failed to schedule scan for pointed aux.
What happens in above scenario is that scan error is already set due
to failed scheduling, but we still send complete received aux. That
is ok, but we do not check for error that is already set and do not
mark data as truncated which results in an assert: if any data were
sent to host, it's expected that we'll have either truncated or
completed flag set on last unref.
The fix is to set truncated flag properly on last chunk of data from
mentioned aux.
> nimble/ll: Fix assert on aux unref during scan

- apps/btshell/src/parse.c
> Replace strtok with strtok_r

- nimble/transport/nrf5340/src/nrf5340_ble_hci.c
This allows to use it regardless of IPC buffer size.
> nimble/transport: Improve nrf5340 transport

- apps/bttester/src/l2cap.c
Added special PSM that identify channels requireing security. These
PSMs correspond to TSPX_psm_authentication_required,
TSPX_psm_authorization_required, TSPX_psm_encryption_key_size_required.
When connection is accepted on these PSMs, link security is checked
and appropriate error is returned when condition is not met.
This affects tests L2CAP/LE/CFC/BV-{11, 13, 15}-C
> bttester: handle special PSMs in l2cap

- apps/ext_advertiser/src/main.c
- apps/ext_advertiser/syscfg.yml
Add new instance that advertises 1650 bytes of periodic data.
> apps: Add periodic advertising instance to ext_advertiser sample

- nimble/controller/src/ble_ll_scan.c
Not sure how this even works, but configuration flags for phys were
never set...
> nimble/ll: Fix phy configuration for initiator

- nimble/drivers/dialog_cmac/src/ble_phy.c
In rare cases, tx-rx transition after rx may not be set properly and
this can result in a connection that is not established properly.
Transition type is set from ble_phy_tx which is called from sw_mac isr
and it should be set before bs_start is fired since it will setup that
transition. This is not a problem on 1st tx, but in case this happens
after rx, it may happen that bs_start is called before ble_phy_tx sets
transition type, so there will be no transition set. However, following
events will have proper transition set so they will act accordingly.
This probably can be recovered in most cases, but in case of extended
connection we will not receive AUX_CONNECT_RSP and will keep "waiting"
for it, so the connection will not be set properly before 1st conn
event and that results in an …
> nimble/phy/cmac: Fix rx-tx-rx transition setup

- docs/index.rst
I am guessing this is a typo :-)
> complaint -> compliant

- nimble/controller/include/controller/ble_ll.h
- nimble/controller/include/controller/ble_ll_ctrl.h
- nimble/controller/include/controller/ble_ll_hci.h
- nimble/controller/src/ble_ll.c
- nimble/controller/src/ble_ll_ctrl.c
- nimble/controller/src/ble_ll_hci.c
- nimble/controller/src/ble_ll_hci_ev.c
- nimble/controller/src/ble_ll_hci_priv.h
- nimble/controller/src/ble_ll_hci_vs.c
- nimble/controller/syscfg.yml
- nimble/include/nimble/hci_common.h
This adds API to allow registration of custom HCI VS commands.
> nimble/ll: Add support for vs hci commands registration

- nimble/controller/src/ble_ll_adv.c
Need to use macros, otherwise it won't work as expected...
> nimble/ll: Fix os_cputime comparisons in ll_adv

- nimble/controller/include/controller/ble_ll_plna.h
- nimble/controller/pkg.yml
- nimble/controller/src/ble_ll.c
- nimble/controller/syscfg.yml
- nimble/drivers/nrf52/src/ble_phy.c
- nimble/drivers/plna/sky66112/pkg.yml
- nimble/drivers/plna/sky66112/src/sky66112.c
- nimble/drivers/plna/sky66112/syscfg.yml
This adds support for RF front-end modules (PA and/or LNA). Driver for SKY66112 module is included.
> nimble/ll: Add support for PA/LNA

- nimble/drivers/nrf5340/src/ble_phy.c
- nimble/drivers/nrf5340/syscfg.yml
WFR is not yet working same way as on nrf52... see todo comment in code
> ll/nrf5340: Add support for PHY GPIO debug

- nimble/controller/src/ble_ll_sched.c
Set the start_time of the first anchor point of new connection to
entry->end_time+1.
For the 32768 Hz crystal in nrf chip, 1 tick is 30.517us.
The connection state machine use anchor point to store the cpu
ticks and anchor_point_usec to store the remainder. Therefore,
to compensate the inaccuracy of the crystal, the ticks of
anchor_point will be add with 1 once the value of
anchor_point_usec exceed 31. If two connections have same
connection interval, the time difference between the two start
of schedule item will decreased 1, which lead to an overlap.
To prevent this from happenning, we set the start_time of sch
to 1 cpu tick after the end_time of entry.
> nimble/ll: Adjust start time of the first anchor point of connection

- nimble/controller/src/ble_ll_conn_hci.c
- nimble/controller/src/ble_ll_ctrl.c
We should use new sca in connsm...
> nimble/ll: Fix sca update handling

- nimble/drivers/dialog_cmac/src/ble_phy.c
This adjusts phy to 31250 tps timer used in LL on CMAC.
> nimble/phy/cmac: Use 31250 tps timer

- babblesim/core/src/argparse.c
This allows to set public bdaddr using -A or --bdaddr command line
option. Accepted formats are both XX:XX:XX:XX:XX:XX and 0xXXXXXXXXXXXX.
> babblesim: Add command line arg to specify bdaddr

- nimble/controller/include/controller/ble_ll_conn.h
- nimble/controller/include/controller/ble_ll_ctrl.h
- nimble/controller/include/controller/ble_ll_hci.h
- nimble/controller/include/controller/ble_ll_utils.h
- nimble/controller/src/ble_ll.c
- nimble/controller/src/ble_ll_adv.c
- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_conn_hci.c
- nimble/controller/src/ble_ll_conn_priv.h
- nimble/controller/src/ble_ll_ctrl.c
- nimble/controller/src/ble_ll_hci.c
- nimble/controller/src/ble_ll_hci_ev.c
- nimble/controller/src/ble_ll_supp_cmd.c
- nimble/controller/src/ble_ll_sync.c
- nimble/controller/syscfg.yml
- nimble/include/nimble/hci_common.h
This adds support for LE Enhanced Connection Update feature (Core 5.3) a.k.a. connection subrating.
> nimble/ll: Add LE Enhanced Connection Update support

- nimble/host/src/ble_att_svr.c
According to Core Specification Version 5.3, Vol 3, Part C
10.3.2.2: " Any notifications received before the security requirements
are met shall be ignored. Any indications received before the security
requirements are met shall be confirmed and then discarded. When a
client reconnects to a server and expects to receive indications or
notifications for which security is required, the client shall enable
encryption with the server."
> host/ble_att_srv: security check for notifications/indications

- apps/bttester/src/bttester.c
- apps/bttester/src/bttester.h
- apps/bttester/src/gap.c
- apps/bttester/src/gatt_cl.c
It's meant to be replacement for GATT one (with GATT Server service).
This service privides asynchronous responses in form of events.
> apps/bttester: add GATT Client service

- apps/btshell/src/cmd.c
The cmd parser expected a variable named peer_type instead of peer_addr_type.
> apps/btshell: Fix peer_addr_type argument parsing

- nimble/controller/src/ble_ll_scan_aux.c
This handles properly the case where AdvA is an identity address in
advertising, but an RPA is used in AUX_CONNECT_RSP.
> nimble/ll: Fix AUX_CONNECT_RSP verification

- nimble/host/include/host/ble_gap.h
- nimble/host/src/ble_gap.c
- nimble/host/src/ble_gap_priv.h
- nimble/host/src/ble_hs_hci_evt.c
- nimble/include/nimble/hci_common.h
- nimble/syscfg.yml
- porting/examples/linux/include/syscfg/syscfg.h
- porting/examples/linux_blemesh/include/syscfg/syscfg.h
- porting/examples/nuttx/include/syscfg/syscfg.h
- porting/nimble/include/syscfg/syscfg.h
- porting/npl/riot/include/syscfg/syscfg.h
LE Power control is BT 5.2 feature. Added support for HCI commands / events for host to controller communication
> nimble/host: Add HCI commands / events for LE Power control

- apps/bttester/src/gap.c
- nimble/host/src/ble_l2cap_sig.c
This should be done before asking application.
This is affecting GAP/CONN/CPUP/BV-05-C
> host: l2cap: check connection parameters in ble_l2cap_sig_update_req_rx

- README.md
> README: Fix FAQ link

- nimble/include/nimble/hci_common.h
> hci_common.h: added missing offset for VS_CSS cmd

- nimble/host/syscfg.yml
This mode requires MITM to be on.
> nimble/host/ble_sm: add restriciton for SC Only

- tools/hci_throughput/README.md
- tools/hci_throughput/targets/nordic_pca10095_app_blehci/pkg.yml
- tools/hci_throughput/targets/nordic_pca10095_app_blehci/syscfg.yml
- tools/hci_throughput/targets/nordic_pca10095_app_blehci/target.yml
- tools/hci_throughput/targets/nordic_pca10095_app_boot/pkg.yml
- tools/hci_throughput/targets/nordic_pca10095_app_boot/syscfg.yml
- tools/hci_throughput/targets/nordic_pca10095_app_boot/target.yml
- tools/hci_throughput/targets/nordic_pca10095_net_blehci/pkg.yml
- tools/hci_throughput/targets/nordic_pca10095_net_blehci/syscfg.yml
- tools/hci_throughput/targets/nordic_pca10095_net_blehci/target.yml
- tools/hci_throughput/targets/nordic_pca10095_net_boot/pkg.yml
- tools/hci_throughput/targets/nordic_pca10095_net_boot/syscfg.yml
- tools/hci_throughput/targets/nordic_pca10095_net_boot/target.yml
> tools/hci_throughput: Added NRF53 targets, README fix

- tools/hci_throughput/check_addr.py
- tools/hci_throughput/hci.py
- tools/hci_throughput/hci_commands.py
- tools/hci_throughput/hci_device.py
- tools/hci_throughput/hci_socket.py
- tools/hci_throughput/main.py
- tools/hci_throughput/throughput.py
- tools/hci_throughput/transport_factory.py
- tools/hci_throughput/util.py
Added option to pass custom transport module.
@sjanc
> tools/hci_throughput: Custom transport option

- tools/hci_throughput/config.yaml.sample
- tools/hci_throughput/hci.py
- tools/hci_throughput/hci_commands.py
- tools/hci_throughput/hci_device.py
- tools/hci_throughput/main.py
- tools/hci_throughput/util.py
> tools/hci_throughput: Added tp tests over encrypted link

- apps/btshell/src/cmd.c
Substitute parameter for "cancel".
> Add "off" param to "scan" command.

- apps/blehr/src/main.c
Don't stop blehr notify if other handles subscribed
Signed-off-by: Hang Fan <fanhang@xiaomi.com>
> apps/blehr: Fix blehr notify stopped incorrectly

- nimble/host/src/ble_l2cap_coc.c
- nimble/host/src/ble_l2cap_coc_priv.h
- nimble/host/syscfg.yml
This allows to process more data while receiving another.
@sjanc
> L2CAP COC: added buffers for incoming SDU

- tools/hci_throughput/README.md
- tools/hci_throughput/check_addr.py
- tools/hci_throughput/config.yaml.sample
- tools/hci_throughput/hci_device.py
- tools/hci_throughput/init.yaml.sample
- tools/hci_throughput/main.py
Updated readme and help descriptions in scripts.
@sjanc
> tools/hci_throughput: updated README.md file, help descriptions

- nimble/controller/include/controller/ble_ll_fem.h
- nimble/controller/pkg.yml
- nimble/controller/src/ble_ll.c
- nimble/controller/src/ble_ll_hci_vs.c
- nimble/controller/syscfg.defunct.yml
- nimble/controller/syscfg.yml
- nimble/drivers/fem/sky66112/include/sky66112/sky66112.h
- nimble/drivers/fem/sky66112/pkg.yml
- nimble/drivers/fem/sky66112/src/sky66112.c
- nimble/drivers/fem/sky66112/syscfg.yml
- nimble/drivers/nrf52/src/ble_phy.c
- nimble/drivers/nrf5340/src/ble_phy.c
- nimble/include/nimble/hci_common.h
This add support for runtime configuration of SKY66112 FEM
> Improvements for SKY66112

- README.md
Point to know external projects that use NimBLE.
> README: Add some notes about external projects using NimBLE

- nimble/drivers/nrf5x/src/ble_hw.c
- nimble/drivers/nrf5x/src/ble_phy.c
- nimble/host/src/ble_gap.c
- nimble/host/src/ble_gap_priv.h
- nimble/host/src/ble_hs_id.c
- nimble/host/src/ble_hs_misc.c
- nimble/host/src/ble_hs_priv.h
2 (cleanup) refactors and one fix for includes for non-mynewt targets
> Bb refactor

- nimble/controller/src/ble_ll_adv.c
Since chain pdus are scheduled from LL while previous aux/chain pdu is already in scheduler, it's possible that previous pdu will be already processed before LL can schedule chain. In such case previous pdu will be sent with AuxPtr offset=0 and we should simply drop subseqent pdus.
> nimble/ll: Fix skipping chain pdus

- nimble/controller/src/ble_ll_scan_aux.c
This is follow up on 8447ec2969. We allow peer RPA to be used in the same way as identity address if we do not have peer IRK, so we also need to update checks for AUX_CONNECT_RSP.
> nimble/ll: Fix initiator on aux with RPA and no peer IRK

- nimble/controller/src/ble_ll_conn.c
This fixes unexpected MIC failure when retransmission happens during encryption start procedure as follows:
- peripheral sends LL_START_ENC_REQ unencrypted, central acks
- central sends LL_START_ENC_RSP encrypted, peripheral acks
- central retransmits LL_START_ENC_RSP for whatever reason
The problem is that peripheral increments rx packet counter after 1st LL_START_ENC_RSP is received, so retransmission is decrypted with different rx packet counter and thus is not valid. We properly ignore MIC failure for retransmission, but then code checks if received PDU is valid in currect state, i.e. encryption start procedure. Since it was not properly decrypted, the PDU type is likely garbage and thus considered as not allowed so we terminate connection with MIC failure.
The "ultimate" fix for such …
> nimble/ll: Fix MIC failure during encryption start

- nimble/host/include/host/ble_gap.h
- nimble/host/include/host/ble_hs_hci.h
- nimble/host/src/ble_gap.c
- nimble/host/src/ble_gap_priv.h
- nimble/host/src/ble_hs_hci.c
- nimble/host/src/ble_hs_hci_evt.c
This adds API to send a vs hci command and an event to handle vs hci events.
> nimble/host: Add APIs to handle vs HCI commands and events

- nimble/host/include/host/ble_gap.h
- nimble/host/src/ble_gap.c
- nimble/include/nimble/hci_common.h
This PR adds support to define macro for setting periodic adv interval .
> nimble/host: Add helper macros to set interval min / max for perdiodic adv

- .github/workflows/build_ports.yml
- .github/workflows/build_targets.yml
- .github/workflows/newt_test_all.yml
Make jobs name more user friendly.
> ci: Improve jobs naming

- nimble/controller/src/ble_ll_adv.c
- nimble/controller/src/ble_ll_conn.c
- nimble/controller/src/ble_ll_conn_hci.c
- nimble/controller/src/ble_ll_ctrl.c
- nimble/controller/src/ble_ll_hci_ev.c
- nimble/controller/src/ble_ll_sched.c
- nimble/controller/src/ble_ll_sync.c
- nimble/host/services/ans/src/ble_svc_ans.c
- nimble/host/src/ble_att.c
- nimble/host/src/ble_hs_hci.c
- nimble/host/src/ble_hs_hci_evt.c
- nimble/host/src/ble_hs_hci_util.c
- nimble/host/src/ble_l2cap_coc.c
- nimble/host/src/ble_store.c
- porting/nimble/src/hal_timer.c
mostly comparison signed vs unsigned and possible un-initialized usage
1 or 2 unused variable warnings (if some ASSERTS are disabled)
> build: fix various compile warnings

- .github/workflows/build_targets.yml
In long term we should think on better mechanism for syncing core and nimble requirements in CI.
> ci: Download external  nrfx repository

- apps/bttester/src/l2cap.c
PSM on which Lower Tester requests connection fully defines what are requirements for request to be accepted. That means that `response` parameter should not be used to return errors from `tester_l2cap_event`, and is not needed.
> apps: bttester: reject L2CAP connections basing on PSM only

- nimble/drivers/fem/sky66403/include/sky66403/sky66403.h
- nimble/drivers/fem/sky66403/pkg.yml
- nimble/drivers/fem/sky66403/src/sky66403.c
- nimble/drivers/fem/sky66403/syscfg.yml
This adds driver for SKY66403-11. It is very similar to SKY66112-11 but PINs configuration has different meaning in transmit mode.
> nimble/drivers/fem: Add support for SKY66403-11

- nimble/drivers/nrf5x/src/ble_phy.c
- nimble/drivers/nrf5x/src/nrf52/phy.c
- nimble/drivers/nrf5x/src/nrf53/phy.c
- nimble/drivers/nrf5x/src/phy_priv.h
- nimble/drivers/nrf5x/syscfg.yml
This allows to set few more power levels on PHY (up to +3dBm).
> nimble/phy/nrf5340: Add support for high voltage on RADIO

- apps/dtm/pkg.yml
- apps/dtm/src/main.c
- apps/dtm/src/parse.c
- apps/dtm/src/parse.h
- apps/dtm/syscfg.yml
This application provides shell interface for Bluetooth DTM. It also provides few extra commands useful for testing (TX power configuration, antenna selection, unmodulated carrier).
> apps: Add DTM shell application

- .github/targets/nordic_pca10056_dtm/pkg.yml
- .github/targets/nordic_pca10056_dtm/target.yml
Adds target for building DTM application.
> ci: Add DTM application target

- nimble/host/include/host/ble_uuid.h
Adds missing macros and structures documentation.
> host/uuid: add doxygen comments for the header file

- nimble/host/include/host/ble_hs_stop.h
Add missing structure members documentation.
> host/hs_stop: add doxygen comments for the header file

- apps/bttester/src/btp_gatt.c
Assigning rsp pointer to new value caused wrong behavior and corrupted response. Data should be copied into buffer instead.
> apps/bttester: fix get_attrs response buffer

- apps/bttester/src/btp_gatt.c
Whole GATT database can be big and data may be missing from rsp.
> apps/bttester: copy whole mbuf chain in get_attrs

- .github/workflows/build_targets.yml
We should move to using "newt upgrade" eventually.
> ci: Fix build due to nrfx update

- nimble/host/include/host/ble_hs_adv.h
Adds missing macros, functions and structures documentation.
> host/hs_adv: add and update doxygen comments for the header file

- apps/advertiser/src/main.c
- apps/blecent/src/main.c
- apps/blecsc/src/main.c
- apps/blehci/src/main.c
- apps/blehr/src/main.c
- apps/blemesh/src/main.c
- apps/blemesh_light/src/main.c
- apps/blemesh_models_example_1/src/main.c
- apps/blemesh_models_example_2/src/main.c
- apps/blemesh_shell/src/main.c
- apps/bleprph/src/main.c
- apps/blestress/src/main.c
- apps/btshell/src/main.c
- apps/bttester/src/main.c
- apps/central/src/main.c
- apps/dtm/src/main.c
- apps/ext_advertiser/src/main.c
- apps/mesh_badge/src/main.c
- apps/peripheral/src/main.c
- apps/scanner/src/main.c
- babblesim/core/src/main_config.c
- babblesim/hw/mcu/nordic/nrf52_bsim/include/mcu/mcu_sim.h
- docs/ble_setup/ble_sync_cb.rst
Mynewt core was updated to use mynewt_main.
> Update samples to use mynewt_main instead of main

- nimble/host/include/host/ble_store.h
- nimble/host/src/ble_store_util.c
Adds missing structures and functions documentation and moves the documentation entries from sources to the header file.
> host/store: add and update doxygen comments for the header file

- ext/liblc3/pkg.yml
Adds LC3 codec implementation from https://github.com/google/liblc3
> ext: add LC3 codec library

- nimble/host/include/host/ble_uuid.h
Corrects variadic macro documentation (BLE_UUID128_INIT). Adds minor formatting improvements.
> host/uuid: Amend doxygen comments in the header file

- babblesim/core/include/core_cm4.h
- babblesim/core/src/main_config.c
- babblesim/edtt/hci_test/src/main.c
- babblesim/hw/mcu/nordic/nrf52_bsim/src/hal_timer.c
that occurred after recent updates (nordic-nrfx v3.3.0.)
> babblesim: Fix build errors

- nimble/host/include/host/ble_gatt.h
Adds missing functions documentation.
Adds minor formatting improvements.
> host/gatt: Amend doxygen comments in the header file

- nimble/host/include/host/ble_iso.h
- nimble/host/src/ble_audio_broadcast_source.c
- nimble/host/src/ble_hs_startup.c
- nimble/host/src/ble_iso.c
- nimble/include/nimble/hci_common.h
This fixes BIG handle assignment from dedicated pool of handles, missing BIG instance pointer checks and missing BIG related HCI events in the LE event mask.
Depends on https://github.com/apache/mynewt-nimble/pull/1702
> nimble/iso: Fix couple of ISO related issues found

- ext/libsamplerate/include/config.h
- ext/libsamplerate/pkg.yml
- ext/libsamplerate/syscfg.yml
Adds libsamplerate library that allows to resample audio streams to different samplerate.
> ext: add libsamplerate library

- nimble/host/src/ble_gap.c
> nimble/host: Fix ble_gap_adv_set_data return code

- .github/check_doxygen.py
- .github/workflows/compliance_check.yml
- .rat-excludes
- Doxyfile
This commit adds a new workflow for Doxygen Check to ensure documentation integrity. The workflow verifies if the Doxygen output contains any warnings.
> ci: Add Doxygen Check workflow

- apps/bttester/src/btp/btp.h
- apps/bttester/src/btp/btp_bap.h
- apps/bttester/src/btp/bttester.h
- apps/bttester/src/btp_bap.c
- apps/bttester/src/btp_core.c
- apps/bttester/syscfg.yml
Add support for autopts BAP test in bttester.
> Add broadcast support in bttester

- nimble/host/src/ble_gap.c
ble_gap_disc() should always results in BLE_GAP_EVENT_DISC and legacy PDUs only.
> nimble/host: Fix reports when using legacy scan with EXT_ADV enabled

- nimble/host/audio/services/pacs/src/ble_audio_svc_pacs.c
Available contexts values are per connection. When value is changed, read access for notification gives BLE_HS_CONN_HANDLE_NONE as conn handle. This was making impossible to fetch the right value. Now, flag was introduced, for marking the changed value.
> host/audio/pacs: fix notifications for available contexts

- nimble/host/audio/include/audio/ble_audio.h
Adds Codec Formats from Assigned Numbers.
> host/audio: add defines for Codec Formats

- nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
This fixes infinite loop while sending BASS Receive state notifications.
> nimble/audio/bass: Fix infinite loop

- nimble/host/src/ble_eatt.c
According to Core Specification Version 5.4, Vol 3, Part G, section 6.2.1, it is not necesarry to check the Server Supported Features characteristic before attempting to establish an EATT bearer.
> nimble/host: remove check srv supported features

- nimble/include/nimble/ble.h
Adds missing macros and structures documentation.
> nimble/ble: Add doxygen comments to the header file

- .github/workflows/ports_syscfg_check.yml
Updates run conditions, so that the action will be triggered on every PR merge. Additionally, adds a scheduled run once a day.
> ci: Fix `Check ports syscfg update` workflow

- .github/workflows/ports_syscfg_check.yml
Updates run conditions, so that the action will not be triggered on forks. 
Changes cron schedule to avoid conflicts with other jobs.
> ci: Update `Check ports syscfg update` workflow

- .github/labeler_cfg.yml
- .github/workflows/labeler.yml
Adds a new label's category for Pull Request size. 
The labels are based on the number of altered lines.
> ci: Upgrade PR labeler

- nimble/controller/src/ble_ll_iso_big.c
Updating BIG event start time by adding interval on every event introduces additional clock drift due to rouding errors on conversion from usecs to ticks.
This fixes the problem by using some event time as constant base and timing for subsqeuent events is calculated relative to that event. This eliminates drift due to calculations.
To prevent overflows in calculations, base event is changed every 30mins.
> nimble/ll: Fix event drift in event start time calculations

- nimble/drivers/dialog_cmac/src/ble_phy.c
TX power is now configured using ble_ll_tx_power_set (instead of ble_phy_tx_power_set) which uses ble_phy_tx_power_round to calculate proper TX power level.
This adds missing implementation for that function in CMAC PHY driver so power level can be properly set.
> nimble/phy/cmac: Fix setting TX power level

- .github/workflows/ports_syscfg_check.yml
Changes the author of commits to bot account.
> ci: Update author in `Check ports syscfg update` workflow

- nimble/host/src/ble_sm.c
- nimble/host/test/src/ble_sm_test.c
- nimble/host/test/src/ble_sm_test_util.c
- nimble/host/test/src/ble_sm_test_util.h
- Ignore security request that was recived after pairing has already started - fixes SM/CEN/PIS/BV-03-C
- Add and fix SM unit tests
> host: sm: ignore security request, add test

- nimble/host/mesh/src/pb_adv.c
Validate if Transaction Continuation PDU can fit into buffer before copying data.
> nimble/mesh: Add check for rx buffer in PB ADV

- nimble/host/audio/services/bass/include/services/bass/ble_audio_svc_bass.h
- nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Update modify source to work with
new mbuf-style data input.
Also a handling for proper receive state fields is added.
Fix a never-ending goto statement returning to goto itself.
> nimble/audio/bass: BASS modify source update

- .github/project_newt_test_all.yml
- .github/workflows/newt_test_all.yml
This should speed up CI a bit.
> ci: Only download required repositories

- nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Remove uncnecessary variable representing
characterisic value in remove source operation
> Remove unnecessary variable

- nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Fixes typo errors in modify source operation
> Fix typos in modify source

- nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Move location of check_bis_sync function
so calling it would not result in build error
> Move check_bis_sync function

- nimble/controller/src/ble_ll_conn_hci.c
- nimble/controller/src/ble_ll_ctrl.c
Now we only reject connection update requests
if host or peripheral tries to change connection
interval
> nimble/ll: Add connection update support for CSS

- apps/blestress/src/rx_stress.c
- apps/blestress/src/stress.c
- apps/blestress/src/stress_gatt.c
- apps/blestress/src/tx_stress.c
This commit removes console_printf usage, adjust log levels to match it's actual content, remove colors etc.
> apps/blestress: refactor logging

- porting/nimble/pkg.yml
- porting/npl/mynewt/pkg.yml
Apparently couple leftovers were present in tree.
> Remove incubator leftovers

- nimble/controller/src/ble_ll_scan_aux.c
Local IRK, if set, is used to generate local RPA in use cases where own address type was set to 0x02 or 0x03 but peer address is not added to resolving list.
If no IRK is set (or set to all-zero), the controller uses NRPA.
> nimble/ll: Use RPA from global local IRK on active scan

- .github/workflows/compliance_check.yml
- uncrustify.cfg
Also park GHA image to specific ubuntu version (24.04).
> ci: Update uncrustify configuration to 0.78

- .github/workflows/compliance_check.yml
> ci: Add missing doxygen dependency

- nimble/host/src/ble_l2cap_sig.c
Add helper that validates if PDU size is valid. This fixes L2CAP/COS/CED/BI-11-C qualification test.
> nimble/host: Refactor L2CAP signaling PDU parsing

- porting/npl/freertos/include/nimble/nimble_npl_os.h
- porting/npl/freertos/src/npl_os_freertos.c
The assert  fails in a debug build otherwise
> port: add ble_npl_hw_is_in_critical implementation

- apps/bttester/src/btp_gap.c
Add proper error check to improve robustness.
> apps/bttester: Add error checks for setting adv data

- .github/workflows/fail_on_error.py
Avoid hardcoded index which causes issues if json structure is modified.
> ci: Make CodeQL fail_on_error.py more robust

- check_workflows.yml
This checks if PRs are using up-to-date workflows.
> ci: Add workflows up-to-date check

- nimble/host/src/ble_hs_stop.c
If `ble_hs_stop_terminate_conn()` returns `BLE_HS_EALREADY`, the stop callback may be triggered before the HCI disconnection Complete event is received. Until that event, some connection-related resources are still in use, and calling APIs like `ble_gatts_reset()` will return BUSY.
Let's use the host stop timeout for the use case with BLE_HS_EALREADY to make sure the stop callback won't be sent too early.
Call HCI reset in the stop sequence to reset the LL state.
> nimble/host: ble_hs_stop: Handle BLE_HS_EALREADY case

- .github/workflows/compliance_check.yml
- .github/workflows/format_file_check.yml
Add workflow to update config file daily.
Remove checking compliance from style-check workflow.
> Add workflow for .clang-format update

- .github/workflows/compliance_check.yml
If skip-style-check label is present print information about skipping the workflow.
> ci: Add information about skipping style check

- .github/workflows/build_cc_target.yml
Validates if things build with GCC 14.
> ci: Add GCC 14 to build matrix

- nimble/host/src/ble_l2cap_sig.c
Procedures needs to be removed based on diconnected connection handle and not all of them. Otherwsie this could lead to droping pending procedure for other connection. Also ble_l2cap_sig_procs list could be corrupted since it is being modified without host lock held.
> nimble/l2cap: Fix cleaning up pending procedures on disconnect
