apache/mynewt-nimble

nimble/include/nimble/hci_common.h, nimble/syscfg.yml
Core Specification 5.3 is available for some time already.
=> nimble: Allow to configure BLE version 5.3

.travis.yml, porting/examples/dummy/Makefile, porting/examples/linux/Makefile, porting/examples/linux_blemesh/Makefile, porting/nimble/Makefile.defs
Some code in NimBLE assumes that pointers are 4 bytes. Until this
is properly fixed build with -m32 to make sure resulting binary
is no misbehaving.
=> ports: Build NimBLE with 32-bit environment

nimble/controller/src/ble_ll.c
This typo caused advertising to break on 1st received req PDU...
=> nimble/ll: Fix rx in advertising state

nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c
When enabling extended advertising it was not possible to send legacy advertisements other than NONCONN. This PR fixes the GAP implementation to also allow advertising legacy connectable, scannable, and directed advertisements.
I am not sure if this is the most beautiful way to solve this, but it was the first thing that came to mind. But  I am open for suggestions for improvement :-)
=> host/gap: improve legacy advertising for BLE_EXT_ADV=1

nimble/include/nimble/hci_common.h
Proper OGF for vendor specific cmd: 0x3F
=> nimble/include: fixed vendor command description

nimble/drivers/nrf52/src/ble_hw.c, nimble/drivers/nrf52/syscfg.yml
The BMD-345 modules are preprogrammed from the factory with a unique
public Bluetooth device address stored in the CUSTOMER[0] and
CUSTOMER[1] registers of the User Information Configuration Registers
(UICR).
=> nimble/phy/nrf: Add support for reading Ublox BMD-345 public address

apps/btshell/src/cmd.c
strl* methods are not always available, let's use snprintf()
for string copy/concat actions in parse_dev_addr, as it allows
us to keep buffer overflow control and NULL termination of string.
=> apps/btshell: fix build on 'native' bsp

targets/nordic_pca10056-blehci-usb/pkg.yml, targets/nordic_pca10056-blehci-usb/syscfg.yml, targets/nordic_pca10056-blehci-usb/target.yml
Target to use nimble controller on Linux with USB.
Target uses some randomly selected USB VID/PID and BT address.
TinyUSB repository must be in project.yml
```
repository.tinyusb:
type: github
vers: 0.7.0
user: hathach
repo: tinyusb
```
=> targets: Add blehci over USB for pca10056

apps/blecsc/syscfg.yml, apps/blehr/syscfg.yml, apps/blestress/src/rx_stress.c, apps/bttester/src/gap.c, nimble/host/mesh/src/shell.c, targets/dialog_cmac/syscfg.yml
ble_hs_id_copy_addr() is used whenever deprecated value was used
for getting public address.
=> apps: remove deprecated BLE_PUBLIC_DEV_ADDR

apps/blecsc/pkg.yml, apps/blehr/pkg.yml, apps/blemesh/pkg.yml, apps/blemesh_light/pkg.yml, apps/blemesh_models_example_1/pkg.yml, apps/blemesh_models_example_2/pkg.yml, apps/blemesh_shell/pkg.yml, apps/blestress/pkg.yml, apps/bttester/pkg.yml, apps/ext_advertiser/pkg.yml, apps/mesh_badge/pkg.yml
Direct dependency on controller is incorrect when
controller runs on another core.
=> apps: Remove controller direct dependency

nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_hci_vs.c, nimble/controller/src/ble_ll_priv.h, nimble/controller/syscfg.yml, nimble/include/nimble/hci_common.h
This command allows to override TX power configured with
BLE_LL_TX_PWR_DBM syscfg value. If 0xff is provided BLE_LL_TX_PWR_DBM
TX power is restored.
=> nimble/ll: Add VS command for setting transmit power

nimble/host/src/ble_gattc.c
If data received in ble_gattc_write_long_rx_prep() doesn't match
data sent in prepare write request we need not only return error in
function, but also send ATT_Execute_Write_Response with flag set to
BLE_ATT_EXEC_WRITE_F_CANCEL.
This is affecting GATT/CL/GAW/BI-32-C
=> host/ble_gattc: Cancel prepered writes if data doesn't match in response

nimble/host/src/ble_hs_startup.c
There's no need to read buffers size if both central and peripheral
roles are not supported. Also host will fail to start if controller
does not ale support those roles since HCI command is not supported
in such case.
=> nimble/hs: Fix startup without central and peripheral supported

nimble/controller/src/ble_ll_scan_aux.c
hci_ev_next was never set to NULL so in case last PDU in chain was
fragmented an assert was triggered since on last chunk (i.e. completed)
we expect hci_ev_next to be NULL.
=> nimble/ll: Fix assert on aux scan

nimble/transport/dialog_cmac/syscfg.yml
Default values always to both non-extadv and extadv builds, the only
difference is event buffer size.
=> nimble/transport/cmac: Fix configuration

nimble/controller/src/ble_ll_adv.c
If periodic advertising instance is enabled, an attempt to set data
with flag other than 'complete' shall return 'command disallowed'.
This fixes HCI/DDI/BI-14-C.
=> nimble/ll: Fix check when setting per adv data

nimble/drivers/dialog_cmac/src/ble_hw.c, nimble/drivers/dialog_cmac/src/ble_hw_priv.h, nimble/drivers/dialog_cmac/src/ble_phy.c
During scan window we restart rx after PDU without reinitializing phy,
this means we do not reenable resolving list. On CMAC this means flags
in resolver are not cleared so once we matched one device, we will
return match for all subsequent devices in that window. So we just need
to clear flag before starting any rx.
=> nimble/phy/cmac: Fix unexpected match on resolving list

nimble/transport/dialog_cmac/cmac_driver/include/cmac_driver/cmac_shared.h, nimble/transport/dialog_cmac/cmac_driver/src/cmac_host.c, nimble/transport/dialog_cmac/cmac_driver/src/cmac_mbox.c
When CMAC is used with HCI bridge over UART we should wait for all
data to be flushed from UART before asserting on error, otherwise we
will lose debug events.
=> nimble/transport/cmac: Flush UART on CMAC error

nimble/controller/src/ble_ll_adv.c
If TX power was tuned with HCI VS command, advertising was using
default value anyway.
=> nimble/ll: Fix not using configured TX power for advertising

nimble/host/mesh/include/mesh/glue.h
Systems can already have MIN / MAX macros defined. Check added to define these macros in nimble code, if they don't exist
=> Add checks in defination of macro MIN / MAX, if they already not present

nimble/controller/syscfg.yml
This should be deprecated after scanner refactor.
=> nimble/ll: Deprecate BLE_LL_EXT_ADV_AUX_PTR_CNT

nimble/controller/src/ble_ll_scan.c
Fall-through for ll_state was not handled properly after some changes
and this means scan proc could disable phy mid-event.
=> nimble/ll: Fix scan proc handling

apps/blehci/pkg.yml, apps/blehci/syscfg.yml, apps/blehcibridge/pkg.yml, apps/blehcibridge/syscfg.yml
So far blehci always used console/stub.
For debugging purpose it may be useful to enable console without
modifying blehci application pkg.deps.
Default value is still stub.
=> apps/blehci: Add full console option

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/include/controller/ble_ll_ctrl.h, nimble/controller/include/controller/ble_ll_sched.h, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_conn_hci.c, nimble/controller/src/ble_ll_conn_priv.h, nimble/controller/src/ble_ll_ctrl.c, nimble/controller/src/ble_ll_hci_vs.c, nimble/controller/src/ble_ll_sched.c, nimble/controller/syscfg.yml, nimble/include/nimble/hci_common.h
This replaces existing implementation of connection strict scheduling with a new one that allows host to modify scheduling in runtime.
In the simplest case a slot duration and number of slots per period have to be configured. This determines scheduling interval (slot duration) and connection interval for each connection (slot duration * slots per period). Each new central connection will now be scheduled at slot boundary and have the same connection interval, this guaranteed that two connections won't overlap.
By default, for each new connection 1st unused slot is allocated. However, it's possible to allocate specific slot to each connection using hci_vs command in 2 ways:
- set slot for new connection prior to sending connection create command,
- set slot for existing connection at any …
=> nimble/ll: New connection strict scheduling

nimble/drivers/nrf52/src/ble_phy.c
Only 1M and 2M are supported, no need for LE Coded.
=> nimble/phy/nrf: Update timings for BabbleSim

babblesim/edtt/hci_transport/src/ble_hci_edtt.c, babblesim/edtt/hci_transport/src/edtt_driver_bsim.c, babblesim/hw/bsp/nrf52_bsim/syscfg.yml
This reworks events handling in EDTT.
The "service_events" routine is now handled in separate task which
blocks until new event is put in queue. This is possible since we use
os_eventq to pass events and this means any get from queue will put
task to sleep properly and trigger context switch if necessary.
The blocking edtt_read() will now sleep if not data is available instead
of advancing time machine forward so it does not interfere with timing.
OS_TICKS_PER_SEC was increased to 1024 to have better granularity and
allow ~5ms sleep time for edtt poller task as required.
Also some non-LL code is simplified to use simple calloc/free as it does
not really seem to be cessary to use mempools there, i.e. we just need
some memory block to pass data and it does not really matter how it's …
=> babblesim/edtt: Refactor queue handling

nimble/controller/src/ble_ll_conn.c
We can handle such PDU in isr, it will be then ignored in LL.
This fixes LL/CON/CEN/BI-14-C and LL/CON/PER/BI-17-C.
=> nimble/ll: Do not nak PDU with RFU LLID

nimble/controller/src/ble_ll_scan_aux.c
We should compare TargetA type in AUX_CONNECT_RSP to TxAdd bit in
AUX_CONNECT_REQ.
=> nimble/ll: Fix checking AUX_CONNECT_RSP

nimble/transport/nrf5340/src/nrf5340_ble_hci.c
ipc_nrf5340_recv was called in nrf_5340_ble_hci_init(), this function
enabled BLE IPC channel if though host transport did not register yet.
If that jump to NULL pointer happens.
To prevent this IPC channel is configured after transport callbacks are
setup. And only then interrupt is enabled for BLE IPC channel.
=> transport/nrf5340: Fix IPC race condition

nimble/transport/nrf5340/src/nrf5340_ble_hci.c
This makes it a lot easier to port Nimble to other platforms beside Mynewt.
Tested on NRF5340 on host + controller
=> nrf5340: dont depend on mynewt.h, but only on sysinit.h

.travis.yml
We moved to more recent OSX version that do not support 32-bit images
anymore co can't do "newt test" on osx.
=> travis: Remove newt test on osx

nimble/controller/src/ble_ll_hci.c, nimble/controller/syscfg.hbd.yml, nimble/controller/syscfg.yml
This adds option to enable some hacks to allow controller to be
initialized by dual-mode host. It basically fakes some HCI command that
we do not support since they are not relevant for BR/EDR, but it allows
for NimBLE controller to be used as a Bluetooth controller e.g. in
Windows 10, at least to some extent.
This option is not intended to be used for production setup, it should
be only used for testing purposes.
=> nimble/ll: Add fake dual mode option

nimble/host/test/src/ble_hs_test_util.c
This fix build regression after BLE_MONITOR was moved to transport.
=> nimble/host: Fix tests compilation

apps/blecsc/src/gatt_svr.c, apps/blehr/src/main.c, apps/blestress/src/rx_stress.c, apps/bttester/src/gatt.c, nimble/host/include/host/ble_gatt.h, nimble/host/mesh/src/pb_gatt_srv.c, nimble/host/mesh/src/proxy_srv.c, nimble/host/services/ans/src/ble_svc_ans.c, nimble/host/services/bleuart/src/bleuart.c, nimble/host/src/ble_att_clt.c, nimble/host/src/ble_gatt_priv.h, nimble/host/src/ble_gattc.c, nimble/host/src/ble_gatts.c, nimble/host/test/src/ble_gatt_conn_test.c, nimble/host/test/src/ble_gatts_notify_test.c
GATT notify/indicate are functions of GATTS, so we should change `ble_gattc_notify`/`ble_gattc_indicate` to `ble_gatts_notify`/`ble_gatts_indicate`
=> Change GATT notify/indicate from gattc to gatts

nimble/transport/nrf5340/src/nrf5340_ble_hci.c
Reading byte-by-byte from IPC to H4 is terribly slow, we should use new
API that can return pointer to an IPC buffer and read directly from
there.
=> nimble/transport/nrf53: Fix slow reads from IPC

nimble/transport/apollo3/pkg.yml, nimble/transport/apollo3/src/apollo3_ble_hci.c, nimble/transport/apollo3/syscfg.yml, nimble/transport/pkg.yml, nimble/transport/syscfg.yml
This changeset brings nimBLE support for Ambiq Apollo3 boards. Accompanying Apollo 3 mynewt-core changes can be found here:
https://github.com/apache/mynewt-core/pull/2784
=> Ambiq Apollo3 nimBLE Support

nimble/controller/src/ble_ll_supp_cmd.c
Read Remote Version Information command bit was not set in supported
HCI commands bitmask.
=> nimble/ll: Fix missing Read Remote Version Info in supported commands

nimble/controller/include/controller/ble_ll.h, nimble/controller/src/ble_ll.c
BLE_LL_ASSERT() now calls ble_ll_assert() which decides whether to break
or send hci_vs event. This significantly reduces code size since there's
no need to include all the branches and calls for each BLE_LL_ASSERT.
Also for hci_vs we only need base file name (i.e. without path) so we
can strip it - __buildiin_strrchr is evaluated during compilation.
This reduces code size for debug build with all features enabled by 5K.
=> nimble/ll: Optimize BLE_LL_ASSERT

nimble/controller/src/ble_ll_conn_hci.c, nimble/controller/src/ble_ll_sync.c, nimble/include/nimble/hci_common.h
There are some new parameter values added in 5.3 to control duplicate
filtering. Since we do not support ADI in periodic advertising, we
simply return a proper error. Note that error is defined only for
HCI_LE_Periodic_Advertising_Create_Sync but we add the same behavior for
other commands also, as otherwise that would not make any sense.
=> nimble/ll: Adjust periodic sync HCI commands to 5.3

nimble/host/src/ble_hs_hci_evt.c
This adds a missing event type in the extended advertising legacy type decoding.
Without this, scan responses would be missed if the PDU was ADV_SCAN_IND.
=> nimble/host: Add missing legacy scan response event type.

nimble/controller/include/controller/ble_ll.h, nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_conn_hci.c, nimble/controller/src/ble_ll_conn_priv.h, nimble/controller/src/ble_ll_ctrl.c
Global channels map is also used by adv code. This fixes build without
central/peripheral roles enabled.
=> nimble/ll: Move global channel map out of ble_ll_conn

nimble/host/mesh/src/pb_gatt_srv.c, nimble/host/mesh/src/pb_gatt_srv.h, nimble/host/mesh/src/proxy_srv.c
We should use connection descriptor from event, as connection no longer
exists.
=> host/mesh: fix disconnect

apps/bttester/src/l2cap.c
Previously, in listen() we used command response parameter straight
away. In fact, this parameter is not an error that shall be returned
when peer creates L2CAP connection with IUT, but value defined in BTP
spec. Now it's translated into CoC error code before passing to
ble_l2cap_create_server() as tester_l2cap_event argument.
=> apps/bttester: make L2CAP listen response parameter consistent with btp

nimble/host/src/ble_gap.c
In `ble_gap.c`, as `params->latency` is of `unsigned uint16_t` type and `BLE_HCI_CONN_LATENCY_MIN` is `0`, the check `(params->latency < BLE_HCI_CONN_LATENCY_MIN)` will always be false and hence can be dropped.
This can give below warnings if custom compiler options are used while compiling the code.
```
warning: comparison is always false due to limited range of data type [-Wtype-limits]
```
=> nimble/host: Remove redundant check in connection latency

nimble/host/src/ble_store_util.c
Issue:
- When storage capacity of bonds is over, `ble_gap_unpair_oldest_peer` is called to make space for new bond. Then `ble_store_util_bonded_peers --> ble_store_iterate` are called. The callback `ble_store_util_iter_unique_peer` sets `set->status = BLE_HS_ENOMEM` when `max_peers` indicated by caller to `ble_store_util_bonded_peers` are iterated over in `ble_store_iterate`.   
- When `max_peer`(input parameter to API) is less than stored bonds, `ble_store_util_bonded_peers` returns `BLE_HS_ENOMEM` status code unnecessarily. It results in not freeing space for new bond when `ble_gap_unpair_oldest_peer` is called.
Solution:
- `ble_store_util_bonded_peers` should not return error depending upon `set.status`.
=> nimble/host: Fix error return in `ble_store_util_bonded_peers`

nimble/host/src/ble_sm.c
The bonded flag was not set on new connection in ble_gap_enc_event()
Without this change, the `if (bonded)` was always `false` on re-connection of a bonded peer in: 
https://github.com/apache/mynewt-nimble/blob/0ef8d590db8bc741f3e25610c6e3e6d11dba2c6c/nimble/host/src/ble_gap.c#L5799
=> nimble/sm: Ensure bonded flag is set in sm_result on new pair & bond.

apps/btshell/src/btshell.h, apps/btshell/src/cmd.c, apps/btshell/src/main.c
This allows to specify name prefix that is used to filter out devices
when scanning. Useful in busy environment.
=> apps/btshell: Add scan filtering based on device name

apps/bttester/src/bttester.h, apps/bttester/src/l2cap.c
This PR adds support for argument `options` in BTP command `connect`, which allows us to create ECFC connection on single channel and hold L2CAP credits and manually give them back at chosen moment.
=> apps/bttester: handle options of created L2CAP server

nimble/host/mesh/src/proxy_msg.h, nimble/host/mesh/src/proxy_srv.c
find_client() should return client from clients[conn_handle - 1],
as connection handles are counted from 1, but arrays are indexed from 0.
This will make sure we use all possible connections, and not leave first
element of clients[] as NULL.
=> host/mesh: fix clients array indexing in proxy_srv

nimble/host/util/src/addr.c
The app didn't build on dialog_da1469x-dk-pro board.
Couldn't load random address.
Divided PR: https://github.com/apache/mynewt-nimble/pull/1018
=> nimble/host: no random address fix

nimble/controller/include/controller/ble_ll.h, nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_sync.c
- ble_ll needs to include hal_system.h for hal_debugger_connected()
- ble_ll_sync needs stdlib.h for abs()
- ble_ll_init() can be static/private
=> minor fixes

nimble/transport/pkg.yml
When building an application (eg btshell),
ble_svc_gap_init() is at stage 301
ble_transport_hs_init() happens at the end after 1000
But ble_svc_gap_init calls (through ble_gatts_add_svcs) ble_hs_lock() that uses
the ble_hs_mutex. This mutex is only initialized in ble_hs_init() (via ble_transport_hs_init),
so this must be called first
=> fix init ordering

nimble/transport/emspi/syscfg.yml, nimble/transport/usb/syscfg.yml
No longer used in new transport architecture.
=> nimble/transport: Remove unused syscfg

nimble/drivers/nrf51/src/ble_hw.c, nimble/drivers/nrf52/src/ble_hw.c, nimble/drivers/nrf5340/src/ble_hw.c
Looks like GCC 11.1 doesn't like current code. The looks OK though...
Error: repos/apache-mynewt-nimble/nimble/drivers/nrf52/src/ble_hw.c: In
function 'ble_hw_get_static_addr':
repos/apache-mynewt-nimble/nimble/drivers/nrf52/src/ble_hw.c:118:9: error:
'memcpy' offset [0, 3] is out of the bounds [0, 0] [-Werror=array-bounds]
118 |         memcpy(addr->val, (void *)&NRF_FICR->DEVICEADDR[0], 4);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
repos/apache-mynewt-nimble/nimble/drivers/nrf52/src/ble_hw.c:119:9: error:
'memcpy' offset [0, 1] is out of the bounds [0, 0] [-Werror=array-bounds]
119 |         memcpy(&addr->val[4], (void *)&NRF_FICR->DEVICEADDR[1], 2);
=> nimble/phy/nrf: Fix build with GCC 11.1

nimble/transport/usb/syscfg.yml
Setting USBD_BTH to 1 is required to enable code in TinyUSB stack.
Due to newt limitation this value could not only be set target or
application.
Now USBD_BTH is defined by not set and can be set by this package.
So user can just specify USB transport and USBD_BTH will be set automatically.
This relies on https://github.com/apache/mynewt-core/pull/2834
=> transport/usb: Enable BTH in TinyUSB stack

nimble/controller/include/controller/ble_ll.h, nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_dtm.c, nimble/controller/src/ble_ll_hci.c, nimble/controller/src/ble_ll_rfmgmt.c, nimble/controller/src/ble_ll_scan.c, nimble/controller/src/ble_ll_scan_aux.c, nimble/controller/src/ble_ll_sched.c, nimble/controller/src/ble_ll_sync.c
- change all ble_npl_eventq_put(&g_ble_ll_data.ll_evq, ..) -> ble_ll_event_add(..)
- change all ble_npl_eventq_remove(&g_ble_ll_data.ll_evq, ..) -> ble_ll_event_remove(..)
- rename ble_ll_event_send -> ble_ll_event_add (matches more with remove)
=> nimble/ll: only let ble_ll.c add/remove to ll_evq

nimble/host/src/ble_att_svr.c
If security is not good enough, return BLE_ATT_ERR_INSUFFICIENT_AUTHEN.
If security is enabled, but key is to short, return
BLE_ATT_ERR_INSUFFICIENT_KEY_SZ
=> host/ble_att_srv: fix ble_att_svr_check_perms for SC Only mode

apps/bttester/src/bttester.h, apps/bttester/src/gap.c
When we receive GAP event BLE_GAP_EVENT_REPEAT_PAIRING it means
that we sent security request, but bond is lost - peer sent pair
request in return, which means it doesn't have keys anymore. Inform
Upper tester about it.
=> apps/bttester: add lost bond event

nimble/transport/nrf5340/src/nrf5340_ble_hci.c
The IPC messages are written in 2 parts: the cmd byte and the rest.
It is unneccesary to already interrupt the other core for the first byte,
since it will be interrupted by the 2nd write already.
=> nrf5340: avoid have 2 interrupts for each IPC message

nimble/drivers/nrf51/src/ble_phy.c, nimble/drivers/nrf52/src/ble_phy.c, nimble/transport/include/nimble/transport.h, nimble/transport/include/nimble/transport/monitor.h, porting/nimble/include/hal/hal_system.h, porting/nimble/include/os/os_mbuf.h, porting/nimble/src/nimble_port.c
This PR is a collection of small fixes to NimBLEs porting layer to allow bumping the NimBLE version in RIOT to the newest NimBLE master.
The main changes are composed of:
- fixing the NimBLE porting initialization in `nimble_port.c` by adapting to the changes in the transport structure 
- add `hal_system.h`, as this file is required by the NimBLE controller now
- used the `nrf52_clock_x()` functions in `ble_phy.c` also for the RIOT port
- supress -Wcast-align compiler warnings in `os_mbuf.h` directly (instead of needing to patch the file in RIOT, which we did so far)
=> porting: fix npl to allow NimBLE version bump in RIOT

nimble/controller/src/ble_ll_rand.c
Currently the controller is using jrand48() to generate pseudo
random numbers. For RIOT builds this commit switches to the RIOT
build-in PRNG API, as this has two benefits: i) it saves 500bytes
of flash and ii) jrand48() internally uses malloc, which has been
source to runtime failures in the past.
=> controller: use OS specific PRNG for RIOT builds

nimble/controller/src/ble_ll_hci.c
This allows NimBLE to be initialized as "dual-mode" controller by BlueZ.
Also inquiry "works" a bit better since Inquiry Complete event is
simulated after inquiry duration has elapsed.
=> nimble/ll: Add more HCI commands for fake dual-mode

nimble/transport/apollo3/src/apollo3_ble_hci.c
There was a bug in the Ambiq Apollo3 ACL data transfer logic in which each data chunk in an mbuf was sent individually to the controller instead of aggregating them together. This caused issues with parts of the bluetooth stack such as BLE SMP.
This set of changes also deals with cleaning up pointers, making them 1 byte pointers where possible for simplification.
=> Apollo3: Properly accumulate full ACL packet before sending to BLE controller

nimble/controller/src/ble_ll_ctrl.c, nimble/controller/src/ble_ll_hci.c, nimble/controller/syscfg.defunct.yml, nimble/controller/syscfg.yml
Rename BLE_LL_MFRG_ID to more readable BLE_LL_MANUFACTURER_ID and change
default value to id assigned to Apache Foundation (0x0B65).
=> nimble/ll: Update manufacturer id settings

nimble/controller/src/ble_ll_conn_hci.c
Need to skip conn interval checks if css is disabled.
=> nimble/ll/css: Fix conn create hci with css disabled

nimble/controller/src/ble_ll_conn.c
In rare cases it's possible that 1st connection event is fired before LL
processed new connection, thus its state is set to idle. In such case we
can just skip the event and LL will reschedule to next event, after the
connection is fully created.
=> nimble/ll: Fix race between conn event and created

nimble/controller/src/ble_ll_scan.c, nimble/controller/src/ble_ll_scan_aux.c
It's possible that scheduled aux is being received while scan sm is
being disabled. In such case aux should not be processed since it cannot
be handled properly anyway.
=> nimble/ll: Fix race between aux scan and scan disable

nimble/controller/src/ble_ll_scan.c, nimble/controller/src/ble_ll_scan_aux.c
If direct address was an RPA and controller was not able to resolve it,
the direct address type in extended advertising report shall be set to
0xFE.
This fixes LL/SCN/DDI/BV-71-C.
=> nimble/ll: Fix direct addr type for ext adv reports

nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_conn_priv.h, nimble/controller/src/ble_ll_ctrl.c
Every time a connection is made, the  ble_npl_callout_init() is done.
This causes a timer creation in some NPL cases (eg. FreeRTOS).
The alloc behaviour of auth_pyld_timer is now in sync with ctrl_proc_rsp_timer
that lives in the same struct.
=> ble_conn: fix auth_pyld_timer memleak

nimble/host/src/ble_att_svr.c, nimble/host/src/ble_sm.c, nimble/host/syscfg.yml, porting/examples/linux/include/syscfg/syscfg.h, porting/examples/linux_blemesh/include/syscfg/syscfg.h, porting/examples/nuttx/include/syscfg/syscfg.h, porting/nimble/include/syscfg/syscfg.h, porting/npl/riot/include/syscfg/syscfg.h
This contains 2 commits:
1. rename BLE_SM_SC_LVL to BLE_SM_LVL - this is not SC only setting, but legacy one too
2. Check for SC in pairing request when in SC Only mode
=> Adjusting SC pairing

apps/blehci/pkg.yml, apps/blehci/syscfg.yml
blehci had log/stub hardwired in application.
Now it can be swtiched to log/full in target if needed.
=> apps/blehci: Allow log/full implementation in syscfg

apps/blehr/src/main.c, apps/ext_advertiser/src/main.c, nimble/controller/src/ble_ll.c, nimble/host/src/ble_att_svr.c, nimble/host/src/ble_hs_mbuf.c, nimble/host/src/ble_sm.c
There are small typos in:
- apps/blehr/src/main.c
- apps/ext_advertiser/src/main.c
- nimble/controller/src/ble_ll.c
- nimble/host/src/ble_att_svr.c
- nimble/host/src/ble_hs_mbuf.c
- nimble/host/src/ble_sm.c
Fixes:
- Should read `response` rather than `respose`.
- Should read `measurement` rather than `measurment`.
- Should read `largest` rather than `larget`.
- Should read `instance` rather than `nstance`.
- Should read `application` rather than `applicaiton`.
- Should read `always` rather than `alwyas`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

nimble/host/src/ble_sm.c
If SC_ONLY is enabled fail pairing request if either keysize is to small
OR SC is not supported by peer. Previously it was an AND, which means
both conditions must be true to fail pairing, which is not correct.
=> host/sm: fix check in ble_sm_pair_req_rx

apps/btshell/src/btshell.h, apps/btshell/src/cmd.c, apps/btshell/src/main.c
On default the application has taken "public" as own address type. Now the application checks if public addres is available on the device and if not, on default it uses "random" as own addres type.
It prevents advertising, scanning and connecting errors if the user won't change own address type in console, while working with a device, which has no public address available.
=> apps/btshell: Add default own_addr_type check

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll_conn.c
Continuation events shall be only applied if the next event is not a
subrated event. Also the event counter shall be also updated only for
events with non-empty PDUs received.
This fixes LL/CON/PER/BV-143-C and LL/CON/CEN/BV-145-C.
=> nimble/ll: Fix continuation events handling

porting/npl/nuttx/src/os_callout.c
callout_thread is working for all timeout callout, it need
an endless loop to catch all message.
=> porting/npl/nuttx: fix callout_handler implement

nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_sched.c
Depending on timing, connection anchor point calculated for current
period and requested slot might have already passed at the time
advertising PDU is received and this causes window offset to be
calculated incorrectly. In such case we just move connection to next
period and recalculate anchor point again.
=> nimble/ll/css: Fix window offset for 1st connection event

nimble/controller/src/ble_ll_scan.c
Using LL Privacy to initiate a connection to a new device (i.e. use 0x02
or 0x03 as own address type, peer is using an RPA) requires host to add
peer RPA and our IRK to resolving list. In this case we should allow to
match that RPA as an identity address on resolving list so we can use
proper privacy settings.
Note that this is a bit of an unspecified behavior, i.e. HCI LE Add
Device To Resolving List command parameters indicates that only identity
addresses shall be added to resolving list, but this does not seem to be
specified anywhere and there is no handling for non-identity address
specified. So basically we allow RPA-as-an-identity to be added to
resolving list, then if AdvA RPA does not match resolving list we just
fall through to see if corresponding entry in resolving list …
=> nimble/ll: Fix privacy handling when connecting to a new device

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll_conn.c
Using effective max rx time for connection event calculations is not
optimal since it's possible that time to rx packet with max octets
payload is shorter that effective max rx time. Instead, we should
calculate time it takes to rx packaet with effectiva max octets payload
and use it if less than effective max rx time.
=> nimble/ll: Use OTA max rx time for connection event calculations

nimble/controller/syscfg.yml, nimble/drivers/nrf5340/src/ble_phy.c
This allows to define PA/LNA turn-on time which allows it to fully turn
on before actual rx/tx. Currently only supported by nRF53 PHY.
=> nimble/phy/nrf: Add PA/LNA turn-on time configuration

nimble/host/src/ble_hs.c
Fixes the problem of not putting events such as, for example ble_hs_hci_evt_le_scan_timeout to the queue.
=> nimble/host: Fix host event buffer count

nimble/controller/src/ble_ll_scan.c
We did not check own address type requested for scan when filtering so
we matched random address even if public address was requested and vv.
This fixes LL/DDI/SCN/BV-71-C.
=> nimble/ll: Fix own address type check during scan

nimble/controller/include/controller/ble_ll_sched.h, nimble/controller/src/ble_ll_scan_aux.c, nimble/controller/src/ble_ll_sched.c
We always reserved 5ms slot for aux scan which is way too long for
either 1M or 2M scan. As a result we are sometimes not able to scan
complete chains if there are many concurrent instances being scanned.
Instead, reserve slot for max pdu possible on secondary phy.
=> nimble/ll: Make sane slot reservation for aux scan

nimble/controller/src/ble_ll_scan_aux.c, nimble/include/nimble/ble.h
If aux chain scan failed to schedule, we simply remove aux ptr flag
which results in "complete" event being sent instead of "truncated". We
should mark PDU accordingly and send "truncated" if this is last aux
chain scanned, but there were more to come.
This fixes LL/DDI/SCN/BV-62-C.
=> nimble/ll: Fix ext adv report status when failed to schedule chain scan

nimble/controller/src/ble_ll_adv.c
Ticks were added to usecs and this does not work as expected.
This fixes HCI/DDI/BI-52-C.
=> nimble/ll: Fix periodic data length check

nimble/transport/cdc/pkg.yml, nimble/transport/cdc/src/cdc_hci.c, nimble/transport/cdc/syscfg.yml, nimble/transport/pkg.yml, nimble/transport/syscfg.yml
This adds implementation of TinyUSB CDC class that
that will transmit HCI protocol over USB/CDC class
This change requires https://github.com/apache/mynewt-core/pull/2863 to be merged first
=> nimble/transport: Add CDC transport

nimble/host/src/ble_gap.c
When both roles - peripheral and central where turned off, removed lines where causing
not calling callback function after completing the scan.
=> host/ble_gap.c: Fix failure to run callback on finished scan

nimble/controller/include/controller/ble_ll.h
We should not allow to set subrating feature if controller does not
support subrating.
=> nimble/ll: Fix host controlled features handling

nimble/controller/src/ble_ll.c
Bits 32,33 34 are for connectable advertising during connection state
as central and thus should be reported only if both peripheral and
central roles are enabled.
=> nimble/ll: Fix LE Read Supported States with no peripheral

nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_scan_aux.c
This adds check for advertising/scan response data length when adding
data to advertising instance or changing instance parameters.
This fixes HCI/DDI/BI-62-C.
=> nimble/ll: Check advertising data length

nimble/controller/src/ble_ll_hci_vs.c
PHY was not configured to use new TX power immediatelly. This resulted
in new TX power being used only after advertising event ended.
=> nimble/ll: Fix not setting TX power in HCI VS command

nimble/include/nimble/hci_common.h
This was duplicating BLE_HCI_OCF_VS_CSS_ENABLE and caused assert
on register.
=> nimble/ll: Fix BLE_HCI_OCF_VS_SET_DATA_LEN OCF

nimble/controller/include/controller/ble_phy.h, nimble/drivers/nrf52/src/ble_phy.c
This adds TX-TX transition, initially supported only on nRF52 PHY.
=> nimble/phy/nrf52: Add tx-tx transition

nimble/controller/include/controller/ble_phy.h, nimble/drivers/nrf52/src/ble_phy.c, nimble/drivers/nrf52/syscfg.yml
This enables APIs to support variable T_ifs in PHY. By default 150us is
used but this value can be changed before each transition. After
transition value is reset to default so LL does not need to care about
setting T_ifs everywhere.
This may be useful for scheduling of related events with tight timings.
Disabled by default since it allows for compile-time optimizations.
=> nimble/phy: Add support for variable T_ifs

nimble/drivers/nrf52/src/ble_phy.c
We should call txend before transition as otherwise called code may mess up transition.
=> nimble/ll: Fix txend callback

nimble/controller/include/controller/ble_phy.h, nimble/drivers/dialog_cmac/src/ble_phy.c, nimble/drivers/nrf51/src/ble_phy.c, nimble/drivers/nrf5x/src/ble_phy.c
Some functions are never used by LL and can be considered private so let's make them static.
=> nimble/phy: Make private functions static

nimble/drivers/nrf5x/src/ble_phy.c
LNA was not enabled properly if RX was started "now".
=> nimble/phy/nrf5x: Enable LNA on "start now" rx

apps/blestress/src/stress.c, apps/blestress/syscfg.yml, apps/btshell/src/main.c, apps/btshell/syscfg.yml, nimble/host/src/ble_l2cap_coc.c
1. fix one rx endpoint sdu case
2. updated btshell and blestress to support setting number of sdus
@sjanc
=> L2CAP COC: fix RX endpoint sdus allocation

nimble/controller/src/ble_ll_scan_aux.c
If CRC does not match on AUX_CONNECT_RSP, we should cancel already scheduled connection as otherwise there will be spurious connection timeout as scheduler will run uninitialized connection.
=> nimble/ll: Fix failed CRC on AUX_CONNECT_RSP

nimble/host/include/host/ble_hs.h
Add key distribution masks defines. This can be used to initialize sm_our_key_dist and sm_their_key_dist fields in ble_hs_cfg struct.
=> host: Add defines for Key Distribution settings

nimble/controller/src/ble_ll.c
We should always send assert vs event if enabled, regardless if we'll break due to attached debugger or not. This is useful when using monitor over RTT since using RTT means debugger is attached even though we may not actually have sw debugger running.
=> nimble/ll: Always send assert vs event if enabled

nimble/controller/src/ble_ll_conn.c, nimble/transport/common/hci_ipc/include/nimble/transport/hci_ipc.h, nimble/transport/common/hci_ipc/pkg.yml, nimble/transport/common/hci_ipc/src/hci_ipc.c, nimble/transport/include/nimble/transport.h, nimble/transport/include/nimble/transport/transport_ipc.h, nimble/transport/nrf5340/pkg.yml, nimble/transport/nrf5340/src/nrf5340_ble_hci.c, nimble/transport/src/transport.c
This adds generic IPC transport that should be used as a base for any transport with LL on separate core. It's similar to HCI H4, but has a bit different header to simplify processing and supports internal flow control to make sure LL does not send data that other core does not have free buffers for.
IPC transport requires memory shared between cores to keep track of number of available buffers on application core. Application core will initialize counters to total number of available buffers. Then on each alloc LL will atomically test and decrease relevan counter and will allocate buffer only if that counter was non-zero. The counter will be increased by application core if relevant buffer was freed.
=> nimble/transport: Add generic IPC transport with flow control

nimble/drivers/nrf5x/syscfg.yml
This was removed accidentally when migrating to nrf5x phy.
=> nimble/phy: Add syscfg for variable tifs

nimble/controller/include/controller/ble_ll.h, nimble/controller/include/controller/ble_ll_ext.h, nimble/controller/include/controller/ble_ll_sched.h, nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_scan.c, nimble/controller/src/ble_ll_sched.c, nimble/controller/syscfg.yml
This adds support for scheduling custom items in NimBLE scheduler.
Custom items shall use BLE_LL_SCHED_EXTERNAL type and set LL state to
BLE_LL_STATE_EXTERNAL when executing. When in that state, LL will call
appropriate callbacks as for any other built-in state which shall be
implemented by application. If different types of custom items are used,
they can be differentiated by sched_ext_type field which can have an
arbitrary value set by application.
Note that this featuer is marked as experimental as API is subject to
change.
=>  nimble/ll: Add support for non-LL items in scheduler

nimble/drivers/nrf5x/src/ble_phy.c
We need to store current transition before calling txend callback. This is important in case of tx-tx transition since txend callback will call ble_phy_tx which overwrites current transition.
=> nimble/phy/nrf5x: Fix tx-tx transition

nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_hci_vs.c, nimble/controller/syscfg.yml
This allows to limit (clip) maximum allowed TX power to meet requirements for selected LE PHY power class.
=> nimble/ll: Add option to define maximum allowed TX power

nimble/drivers/fem/sky66112/src/sky66112.c
Make sure we set all configuration to defaults when HCI reset is issued.
=> nimble/fem: Reset SKY66112 to defaults on HCI reset

nimble/transport/include/nimble/transport/transport_ipc.h, nimble/transport/nrf5340/src/nrf5340_ble_hci.c, nimble/transport/src/transport.c
This fixes the build after the recent HCI_IPC changes.
Also these changes now add a dependency from Mynewt/drivers/ipc5430 to the Nimble stack, which IMHO is a no go. This is not fixes in this request.
=> Fix missing includes and missing return (compiler gives error)

nimble/controller/src/ble_ll_sched.c
Reset CSS configuration to defaults on HCI reset. Otherwise we could end up with enabled CSS after HCI reset.
=> nimble/ll: Fix not re-initializing CSS on HCI reset

nimble/controller/src/ble_ll_scan.c
Core Specification 5.3, Vol 4, Part E, 7.8.65:
"If Enable is set to 0x01 and the Host has not issued the HCI_LE_Set_Extended_Scan_Parameters command, the Controller shall either use vendor-specified parameters or return the error code Command Disallowed (0x0C)"
To keep things simple we just reject in such case.
This was affecting HCI/DDI/BV-06-C qualification test case.
=> nimble/ll: Fix enabling extended scan with no configuration

nimble/controller/include/controller/ble_ll_ext.h, nimble/controller/src/ble_ll.c
This adds init and reset calls for external code so it can be initialized and reset properly in sync with LL.
=> nimble/ll: Add init and reset for external code

apps/bttester/src/gap.c, nimble/host/include/host/ble_hs_hci.h, nimble/host/mesh/src/glue.c, nimble/host/src/ble_hs_hci_priv.h, nimble/host/src/ble_hs_hci_util.c, nimble/host/src/ble_hs_id.c, nimble/host/src/ble_sm.c, nimble/host/src/ble_sm_alg.c, nimble/host/src/ble_sm_sc.c
This may be useful to get some random if MCU does not support trng, e.g. as on nRF5340 app core.
=> nimble/ll: Add API to read random data from controller

nimble/transport/syscfg.yml
syscfg conditions should use single quotes
=> nimble/ll: Fix syscfg restrictions

nimble/host/include/host/ble_hs.h, nimble/host/include/host/ble_store.h, nimble/host/src/ble_hs_startup.c, nimble/host/src/ble_sm.c
Application can use new callback to generate keys for new pairing prior to keys distribution. This allows keys to be derived from some other source (e.g. as in Vol 3, Part H, appendix B) instead of just being randomized.
=> nimble/host: Add host callback to provide security keys

nimble/controller/syscfg.hbd.yml
Some BR/EDR commands eg. Read Local Name command have fixed (max allowed HCI event size) return values. If event size is smaller it results in assert.
=> nimble/ll: Require 257 bytes HCI events when enabling fake dual-mode

nimble/host/src/ble_hs_startup.c
If LE Power Control feature is enabled, then host should get relevant events. This PR enables event mask associated with Power control feature.
=> nimble/host: Enabled LE Power control event mask if feature is enabled

nimble/controller/src/ble_ll_conn.c
If connsm is already on css list and has slot index changed, the list may not be sorted properly so in some case item was not re-inseterd properly. To make things simpler, let's just remove item from the list and then find proper place for it bo be inserted, since doing both in single pass is too convoluted.
=> nimble/ll/css: Fix updating css list

nimble/drivers/nrf5x/src/ble_phy.c
Trim values shall be loaded after if toggling power.
=> nimble/phy/nrf5x: Implement NRF5340 errata 158

nimble/controller/src/ble_ll_dtm.c
DTM test uses fixed frequency and PHY mode so there is no need to re-configure those after every packet reception. It is enough to just restart scanning.
=> nimble/ll: Simplify DTM RX test

nimble/drivers/fem/sky66112/include/sky66112/sky66112.h, nimble/drivers/fem/sky66112/src/sky66112.c, nimble/drivers/fem/sky66112/syscfg.yml
This allows to configure default antenna at runtime.
=> nimble/fem: Add runtime default antenna selection to SKY66112

nimble/drivers/fem/nrf21540/include/nrf21540/nrf21540.h, nimble/drivers/fem/nrf21540/pkg.yml, nimble/drivers/fem/nrf21540/src/nrf21540.c, nimble/drivers/fem/nrf21540/syscfg.yml, nimble/drivers/nrf5x/src/nrf53/phy.c
This adds support for nRF21540 FEM.
FEM is controlled via GPIOs, there's no support for SPI.
=> nimble/drivers/fem: Add support for nRF21540

nimble/controller/src/ble_ll_conn.c, nimble/controller/syscfg.yml
This works by allowing to shorten connection event end time by specified number of us. This value should be tuned only after measuring performance as depends on various factors like build optimisation, cache, clock speed etc.
=> nimble/ll: Allow to tune time needed for scheduling next conn event

nimble/controller/include/controller/ble_ll_ctrl.h, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_ctrl.c
If new DLE parameters were matching default values DLE update procedure was not started.
=> nimble/ll: Fix not being able to get back to default DLE values

nimble/controller/src/ble_ll_scan.c
Fixing false possitive compiler error
/home/rymek/projects/bletiny_proj/repos/apache-mynewt-nimble/nimble/controller/src/ble_ll_scan.c:456:12: error: array subscript <unknown> is outside array bounds of 'struct ble_ll_scan_advertisers[0]' [␛]8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Warray-bounds␇-Werror=array-bounds␛]8;;␇]
456 |     memcpy(&adv->adv_addr, addr, BLE_DEV_ADDR_LEN);
=> ll: Fix compiler error

nimble/controller/include/controller/ble_ll_utils.h, nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_ctrl.c, nimble/controller/src/ble_ll_hci.c, nimble/controller/src/ble_ll_hci_vs.c, nimble/controller/src/ble_ll_scan_aux.c, nimble/controller/src/ble_ll_sync.c, nimble/controller/src/ble_ll_utils.c
Use macros provided by utils instead of relying on system providing min and max macros.
=> nimble/ll: Use MIN/MAX macros from ble_ll_utils.h

nimble/host/src/ble_l2cap.c
Removed extra false parameter description of the function ble_l2cap_rx.
=> NimBLE/host: Remove duplicate parameter description

porting/examples/nuttx/main.c
Report here:
https://github.com/apache/nuttx/actions/runs/4098214664/jobs/7067171681
=> porting/nuttx: Fix error: implicit declaration of function 'usleep'

nimble/transport/src/transport.c
This removes extra memory used by ACL pool structures if pool is not used, i.e. count=0. This happens e.g. on combined build since both hs and ll sides use msys instead of transport pool. This can also be set by user if neither central nor peripheral role is enabled and ACL pool is not needed.
=> nimble/transport: Remove ACL pool if not used

nimble/transport/socket/src/ble_hci_socket.c, porting/npl/linux/include/nimble/nimble_npl_os.h, porting/npl/nuttx/include/nimble/nimble_npl_os.h
Report here: https://github.com/apache/nuttx-apps/actions/runs/4102723052/jobs/7076100328
- Fix ble_hci_socket.c:359:5: warning: implicit declaration of function ‘ble_hci_trans_buf_free’
- Fix SYSINIT_PANIC_ASSERT_MSG refinition warning
=> Fix the compiler warning on NuttX

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll_ctrl.c, nimble/controller/syscfg.yml, porting/npl/riot/include/syscfg/syscfg.h
New option allows to select if controller should initiate DLE update automatically for connection. By default it is enabled to not change existing controller behavior.
=> nimble/ll: Add option to control initial DLE update

nimble/controller/src/ble_ll_sync.c
It was possible to exit ble_ll_sync_transfer() without exiting critical section.
=> nimble/ll: Fix missing critical section exit in PAST

nimble/doc/transport.md
Trivial copy-paste mistake fix.
=> nimble/doc: Fix typo in HCI transport document

.github/workflows/ports_syscfg_check.yml
It seems that occasionally this fails on GHA but doesn't fail locally. This will help to debug this.
=> ci: Add debug output for ports syscfg updates

nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c, nimble/host/src/ble_gap_priv.h, nimble/host/src/ble_sm.c
This way app does not need to query for new ID address.
=> nimble/host: Add peer id addr to identity resolved event

nimble/transport/socket/src/ble_hci_socket.c
ble_hci_socket.c: fix warning 'len' may be used uninitialized in this function [-Wmaybe-uninitialized]
=> ble_hci_socket.c: fix NuttX CI error

nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c
This adds two new GAP APIs:
void ble_gap_conn_foreach_handle(ble_gap_conn_foreach_handle_fn &ast;cb, void &ast;arg)
API can be used to call function declared by the user for every connection that is currently established. As arguments, it takes a pointer to the function, that will be called and a void pointer, which is used to pass the optional argument of any type to the called function. Function from passed pointer should return an int value and take two arguments - uint16_t for conn_handle and void&ast; for the optional argument (see ble_gap_conn_foreach_handle_fn typedef).
int ble_gap_conn_func_handle_by_addr(const ble_addr_t &ast;addr, uint16_t &ast;out_conn_handle)
API will look for the connection with address specified in the first argument and if it succeds, it will write the …
=> nimble/host: Add connection handle related GAP APIs

.github/workflows/build_targets.yml, .github/workflows/newt_test_all.yml, .github/workflows/ports_syscfg_check.yml
This should make it easier for upgrading dependencies in newt.
=> ci: Use latest go for building newt

nimble/drivers/nrf5x/src/ble_phy.c
When scheduling relative to TX start time we should also adjust for delay between radio event and actual TX time.
=> nimble/phy/nrf5x: Fix tx-tx timing

porting/examples/nuttx/main.c
porting/nuttx/example: perform initialization if not done by NSH.
For example, when Nimble NuttX example is the entry point for users applications.
=> porting/nuttx/example: perform initialization if not done by NSH

nimble/host/src/ble_att_clt.c
This PR attempts to put debug related code under DEBUG flag. If DEBUG flag is disabled, the existing code still executed the copying of txom contents in a loop, which wastes time.
=> nimble/host: Added debug flag around debug related code

apps/btshell/src/cmd.c, nimble/host/include/host/ble_store.h, nimble/host/src/ble_sm.c, nimble/host/src/ble_store.c, nimble/host/store/config/src/ble_store_config.c, nimble/host/store/ram/src/ble_store_ram.c, nimble/host/test/src/ble_sm_test_util.c
While re-pairing ble_store_config_find_sec function was checking peer address, ediv and random number. Even if peer address was the same, the bond could be recognized as not the one we was looking for, because ediv and random number could be different. This was causing issues when the BLE_STORE_MAX_BONDS syscfg val was used. Re-pairing to the same device was treated as pairing to the new device and if current number of bonds was the same as BLE_STORE_MAX_BONDS, the re-pairing was failing.
=> nimble/host: Update existing bond while re-pairing

nimble/controller/include/controller/ble_ll_scan.h, nimble/controller/include/controller/ble_ll_scan_aux.h, nimble/controller/include/controller/ble_ll_sched.h, nimble/controller/src/ble_ll_scan.c, nimble/controller/src/ble_ll_scan_aux.c, nimble/controller/src/ble_ll_sched.c
We should include clock drift due to sleep clock accuracy and jitter
when calculating aux scan start time (Core 5.3, Vol 6, Part B, 4.2.2).
Slot duration calculation should also include the above and possible
drift due to offset accuracy.
=> nimble/ll: Fix aux scan timing

nimble/controller/src/ble_ll_hci.c
Any non-zero value for num ACL packets and packet length is valid. The quoted text from spec referrerd to command and event packets, not ACL packets.
=> nimble/ll: Fix HCI_Host_Buffer_Size

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_conn_hci.c
If host provides maximum CE length (when initiating connection or updating its parameters) LL will take it into account when checking if more packages can be send in current event.
=> nimble/ll: Account for host provided Max_CE_length

nimble/host/src/ble_gattc.c
When attempting to compile code with -O2 optimization enabled, observe compilation errors: 
In function 'ble_gattc_find_inc_svcs_cb',
inlined from 'ble_gattc_find_inc_svcs_rx_adata' at /home/rahul/development/gitlab/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_gattc.c:2008:16:
/home/rahul/development/gitlab/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_gattc.c:1809:14: error: 'service' may be used uninitialized [-Werror=maybe-uninitialized]
1809 |         rc = proc->find_inc_svcs.cb(proc->conn_handle,
|              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1810 |                                     ble_gattc_error(status, att_handle),
|                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1811 | …
=> nimble/host: Fix compilation issues observed by enabling -O2 optimization

README.md
NimBLE have been ported to work on the Open IOT SDK, which support freeRTOS, RTX and ThreadX
=> doc: Add a new external NimBLE port to README

apps/blestress/src/rx_stress.h
This fixes include path after nrfx was switched
to used github repository
This is needed when https://github.com/apache/mynewt-core/pull/2989 is merged
=> apps/blestress: Fix nrfx include path

nimble/controller/include/controller/ble_ll_hci.h, nimble/controller/include/controller/ble_ll_sync.h, nimble/controller/src/ble_ll_conn_hci.c, nimble/controller/src/ble_ll_conn_priv.h, nimble/controller/src/ble_ll_hci.c, nimble/controller/src/ble_ll_sync.c
Updating Min/Max CE Length can be done without triggering LL procedure. We can do that if current connection parameters fits parameters parameters provided in HCI command. Note that this is also valid for Connections Strict Scheduling.
=> nimble/ll: Allow to locally update connection min/max CE length

nimble/drivers/nrf5x/src/ble_phy.c
FreeRTOS assumes a max irq priority for IRQs that are allowed to do system calls. This is set to 5 by default, so we use the highest allowed for the Radio.
=> porting/FreeRTOS: fix IRQ priority

nimble/controller/src/ble_ll_sync.c
The assert only works on MyNewt since the ev field does not exist in other versions of ble_npl_event
=> mynewt: fix assert

nimble/host/src/ble_gap.c, nimble/include/nimble/hci_common.h
Removed the extra status field in the enhanced read transmit power level
=> nimble/host: Removed the extra status field in the enh read transmit power level

apps/bttester/syscfg.yml, nimble/include/nimble/hci_common.h, nimble/syscfg.yml
Adds configuration for Core Specification 5.4
=> nimble: Allow to configure BLE version 5.4

nimble/controller/syscfg.yml, nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c, nimble/host/src/ble_gap_priv.h, nimble/host/src/ble_hs_hci_evt.c, nimble/host/src/ble_hs_startup.c, nimble/syscfg.yml
This adds "experimental" tag for BIGInfo sycfgs and changes the name of host's syscfg to describe it better.
=> nimble: Add experimental tag for BIGInfo syscfgs

apps/bttester/src/atomic.h, apps/bttester/src/bttester.c, apps/bttester/src/bttester.h, apps/bttester/src/bttester_pipe.h, apps/bttester/src/gap.c, apps/bttester/src/gatt.c, apps/bttester/src/gatt_cl.c, apps/bttester/src/glue.c, apps/bttester/src/glue.h, apps/bttester/src/l2cap.c, apps/bttester/src/main.c, apps/bttester/src/mesh.c, apps/bttester/src/uart_pipe.c
bttester was initially ported from Zephyr. This app is independent now and should follow Mynewt Coding Standards.
=> apps: bttester: make bttester code compliant with Mynewt code style

apps/blecent/src/main.c
apps/blecent: Fix incorrect return value handling in blecent_should_connect. 
ble_hs_adv_parse_fields can return a non zero code as error. However, a non-zero value is being treated as success in the application. So even if parsing of fields fails, the code would still assume it to be successful and proceed.
=> apps/blecent: Fix incorrect return value handling in blecent_should_connect.

nimble/transport/socket/pkg.yml
This caused double call to hci socket init function and triggered assertion while trying to run apps on native.
@andrzej-kaczmarek
=> nimble/transport: Remove initialization of hci socket from sysinit

nimble/controller/src/ble_ll_hci_supp_cmd.c
BLE_LL_BT5_PHY_SUPPORTED is defined in ble_ll.h so if that file is not included, we calculate incorrect hci supported cmds bitmask.
=> nimble/ll: Fix hci supported cmds

nimble/host/include/host/ble_gap.h, nimble/include/nimble/hci_common.h
Current code had unsigned data type for power level and delta values. Since negative numbers are possible, so modified code to have signed data types.
=> nimble/host: Fix data type of power level and delta to handle negative values

nimble/controller/include/controller/ble_ll_ctrl.h, nimble/controller/src/ble_ll_hci_ev.c
This adds helper to send vs hci event with payload formatted in
printf-like manner. This shall not be used in any publicly available
code, it's only intended for local debugging purposes.
=> nimble/ll: Add debug printf vs hci event

apps/bttester/src/gatt_cl.c
There is no need to call `gatt_buf_add` when `gatt_buf` if filled using pointer `chr` from `gatt_buf_reserve`. This caused sending malformed data to BTP reposnse event.
=> apps: bttester: fix attribute reporting in read by UUID

apps/bttester/src/gatt.c
Local Included Service(s) values are retrieved using `ble_att_svr_read_handle`, which will lead to calling `entry->ha_cb` for Included Service. This will be `ble_gatts_inc_access`, which will not add UUID if it's not of 16 bit type. Use 16 bit UUID for included service.
`out_att_err` is now set to 0 by default - it may be not overwritten if no error occured. This will lead to undefined behavior and incorrect data in BTP response.
=> apps/bttester: fix retrieving app included services

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_ctrl.c
The instant for connection update was calculated at the time PDU was
enqueued in connsm. This caused new conn params to be always applied at
instant regardless if PDU was event dequeued for tx, e.g. in case there
were lots of data PDUs to be send before control PDU.
Currently we calculate instant when PDU is dequeued to make sure this is
the next PDU to be sent and thus instant is valid.
=> nimble/ll: Fix connection update instant calculation

nimble/controller/include/controller/ble_ll_sched.h, nimble/controller/src/ble_ll_sched.c, nimble/controller/src/ble_ll_sync.c
Make sync sched handling more like other items, i.e. scheduler item is
set via internal API and scheduling funcs just do the necessary
scheduling.
=> nimble/ll: Simplify sync sched handling

apps/bttester/src/gap.c
Sometimes it's simpler to call pair() even when procedure is already active. Do not fail command in this case, as it doesn't influence already ongoing procedure.
=> apps/bttester: do not fail pairing if it's already active

nimble/host/src/ble_sm.c
Different status shall be returned when key size is to small and when SC is not supported.
This is affecting GAP/SEC/SEM/BV-23-C
=> host/sm: split error check for SC Only requirements in Pair Response

nimble/drivers/dialog_cmac/src/ble_rf.c
Chip variant detection does not work properly in ble_rf_init since it may be called when PD_SYS is disabled. We better do this in core on CMAC startup as PD_SYS is always enabled at that time.
=> nimble/phy/cmac: Move chip variant detection to core

nimble/transport/pkg.yml, nimble/transport/syscfg.yml, nimble/transport/uart_ll/pkg.yml, nimble/transport/uart_ll/src/hci_uart.c, nimble/transport/uart_ll/syscfg.yml
This is the same as standard "uart" transport except it's for LL side which means it can be used for NimBLE host to talk to external controller. Enable it by "BLE_TRANSPORT_LL: uart_ll".
=> nimble/transport: Add UART transport for external controller

nimble/drivers/nrf5x/src/ble_phy.c
Errata specifies only NRF_RADIO registers that should be copied from FICR, code copied all registers from TRIMCNF.
Now only NRF_RADIO registers are copied as part of Errata 158 implementation.
=> nimble/phy/nrf5x: Update NRF5340 errata 158

porting/examples/nuttx/main.c, porting/npl/nuttx/src/os_callout.c, porting/npl/nuttx/src/os_task.c
This change adds name assignment for the threads created by nimBLE in NuttX based systems, so it is easier to track them in the process tree.
=> porting/npl/nuttx: add support for thread names

nimble/host/src/ble_att_svr.c
This change fixes warnings that appeared when compiling with GCC 13.1.0:
```
/home/alex/git/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_att_svr.c:1838:16: error: 'entry' may be used uninitialized [-Werror=maybe-uninitialized]
1838 |             if (entry == NULL) {
|                ^
/home/alex/git/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_att_svr.c:1713:31: note: 'entry' was declared here
1713 |     struct ble_att_svr_entry *entry;
|                               ^~~~~
/home/alex/git/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_att_svr.c:1846:18: error: 'start_group_handle' may be used uninitialized [-Werror=maybe-uninitialized]
1846 |             rc = ble_att_svr_read_group_type_entry_write(txom, mtu,
| …
```
=> Fix gcc 13 warnings

nimble/host/include/host/ble_hs_log.h
Add missing macros and functions documentation.
=> host/hs_log: add doxygen comments for the header file

nimble/controller/src/ble_ll.c, nimble/host/mesh/src/adv_legacy.c, nimble/host/src/ble_gap.c, nimble/host/src/ble_hs.c, nimble/host/src/ble_hs_shutdown.c, nimble/transport/socket/src/ble_hci_socket.c, porting/nimble/include/log/log.h, porting/nimble/src/hal_timer.c
Currently there's a mix of `#if MYNEWT` and `#ifdef MYNEWT` used in the codebase to check if the environment is Mynewt or not. This is incompatible with `-Wundef`, so switch common parts of the code to uniformly use `#ifdef`.
=> if MYNEWT -> ifdef MYNEWT

porting/npl/linux/src/os_task.c
Per `pthread_yield(3)`:
```
This call is nonstandard, but present on several other systems.
Use the standardized sched_yield(2) instead.
```
=> porting/npl/linux: Replace pthread_yield() with sched_yield()

nimble/drivers/native/src/ble_phy.c
This is necessary to build native target on 64-bit architecture
=> native: Change pointer type casting to uintptr_t

nimble/host/src/ble_gap.c
Fix for warnings appeared while building with gcc 13.1.0
```
In function 'ble_gap_call_event_cb',
inlined from 'ble_gap_preempt_done' at ../../../../../../components/bt/host/nimble/nimble/nimble/host/src/ble_gap.c:6755:9:
../../../../../../components/bt/host/nimble/nimble/nimble/host/src/ble_gap.c:769:14: error: 'master_cb' may be used uninitialized [-Werror=maybe-uninitialized]
769 |         rc = cb(event, cb_arg);
|              ^~~~~~~~~~~~~~~~~
../../../../../../components/bt/host/nimble/nimble/nimble/host/src/ble_gap.c: In function 'ble_gap_preempt_done':
../../../../../../components/bt/host/nimble/nimble/nimble/host/src/ble_gap.c:6704:23: note: 'master_cb' was declared here
6704 |     ble_gap_event_fn *master_cb;
|                       ^~~~~~~~~
In function 'ble_gap_call_event_cb', …
```
=> nimble/host: fix gcc 13 warnings

apps/bttester/src/btp_core.c
If statements encapsulates GATT_CL too.
=> apps/bttester: fix preprocessor directive for registering Mesh service

apps/bttester/src/btp/btp_gap.h, apps/bttester/src/btp_gap.c
high_duty_cycle is defined in flags field that is 2 octet long, as first bit.
=> apps/bttester: fix start_direct_adv command

nimble/controller/src/ble_ll_scan.c
LL_STATE_BIG was not handled properly when trying to start scan window.
=> nimble/ll: Fix assert on scan start

apps/bttester/src/btp_gatt.c
Characteristic values can be long and not fit into single os_mbuf - copy whole chain instead.
=> apps/bttester: copy whole buffer to response of get_attr_val

apps/bttester/src/btp_gap.c
Encapsulated cases in correct configuration check
(BTTESTER_PRIVACY_MODE). Used simple bit comparison, as glue module was dropped.
=> apps/bttester: fix check for address type in advertising_start()

porting/npl/linux/src/os_atomic.c, porting/npl/linux/src/os_mutex.c
porting/npl/linux: support C library (such as musl) which didn't  have PTHREAD_MUTEX_RECURSIVE_NP defined
=> porting/npl/linux: support C library which didn't have PTHREAD_MUTEX_RECURSIVE_NP

nimble/host/include/host/ble_gatt.h
Adds missing macros and structures documentation. Corrects arguments names in functions documentation.
=> host/gatt: add and update doxygen comments for the header file

nimble/host/include/host/ble_hs.h
Adds missing macros and structures documentation.
=> host/hs: add doxygen comments for the header file

nimble/host/include/host/ble_uuid.h, nimble/host/src/ble_uuid.c, nimble/host/test/src/ble_uuid_test.c
Added function that converts 128-bit UUID given as string to a struct ble_uuid128_t.
@sjanc @andrzej-kaczmarek
=> host: Convert string 128-bit UUID to ble_uuid128_t

.github/workflows/compliance_check.yml
RAT 0.16 will have support for SPDX but snapshots links are not permanent so for time being use 0.15.
=> ci: Use RAT 0.15 for compliance check

apps/bttester/syscfg.yml
EATT causes issues with tests GAP/SEC/SEM/BV-{65-67}-C. It is experimental feature and should not influence config for current test plan.
=> apps/bttester: disable EATT in default config

nimble/drivers/nrf5x/src/ble_phy.c, nimble/drivers/nrf5x/syscfg.yml
This allows to extend T_ifs (inter-frame spacing) by additional microseconds to improve interoperability with peripherals that send packets too late (eg 153us). This prolongs reception time by additional microseconds. Defaults to 2us to improve operations with devices already on the market.
=> nimble/phy/nrfx: Add support for extending T_IFS

nimble/host/include/host/ble_gap.h
Adds missing macros, functions and structures documentation. Corrects arguments names in functions documentation.
=> host/gap: add and update doxygen comments for the header file

nimble/host/src/ble_l2cap_sig.c
Next should be updated to point at the previous element in the list for removal to work correctly.
(Found and reported by clang-analyzer - [output](https://gist.githubusercontent.com/rojer/e8aaa84619625e1064904177ace11955/raw/28e6d4392acb9446bd588434d0578bb2d4952883/gistfile1.txt))
=> Fix a bug in ble_l2cap_sig_extract_expired

porting/npl/linux/src/os_atomic.c
Fix wrong mutex attributes in pthread_mutexattr_settype. It can cause deadlock after locked.
=> porting/linux: fix deadlock in ble_npl_hw_enter_critical

nimble/host/src/ble_gap.c, nimble/transport/src/monitor.c
npl_mutex_init may return a non-zero value in case of failure. At certain places, the check is missing to capture the return value. Added the same.
=>  nimble/host: Added return type handling for npl_mutex_init

nimble/transport/common/hci_h4/src/hci_h4.c
`min(a, b)` was not defined but was used at
https://github.com/apache/mynewt-nimble/blob/690945db8b4bae8733f786cec861dc2bb90e518b/nimble/transport/common/hci_h4/src/hci_h4.c#L100
https://github.com/apache/mynewt-nimble/blob/690945db8b4bae8733f786cec861dc2bb90e518b/nimble/transport/common/hci_h4/src/hci_h4.c#L198
=> transport/hci_h4: fix compilation error

porting/nimble/src/nimble_port.c
When using external controller, `ble_transport_ll_init()` was not run because of `NIMBLE_CFG_CONTROLLER` was not defined, resulting in assertion failed and system crashed.
But under current architecture `ble_transport_ll_init()` should also be run to initialize the communication interface, no matter `NIMBLE_CFG_CONTROLLER` is defined or not.
=> porting/nimble_port: fix controller not initialized

nimble/host/include/host/ble_eddystone.h
Adds missing macros documentation and corrects an argument name in function's header.
=> host/eddystone: add and update doxygen comments for the header file

.github/workflows/compliance_check.yml
SPDX support is only available in unreleased RAT snapshot so for now use latest snapshots.
=> ci: Use latest RAT snapshots

nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c, nimble/host/src/ble_gap_priv.h, nimble/host/src/ble_hs_hci_evt.c, nimble/host/syscfg.yml
This adds option to enabled additional GAP event which is called for a HCI event that host doesn't know how to handle. It can be used to test controller features that host doesn't yet support.
=> nimble/host: Add optional GAP event for unhandled HCI events

nimble/host/include/host/ble_gap.h
This adds the declarations of two GAP APIs that were previously defined in the ble_gap.c. Now both APIs can be used in other source files.
=> nimble/host: Add connection handle realated GAP APIs to header file

apps/btshell/src/cmd_l2cap.c
parse_arg_byte_stream_custom takes unsigned int as argument for result lenght.
=> apps/btshell: fix cmd_l2cap_reconfig command

porting/npl/freertos/src/npl_os_freertos.c
As mentioned in the in_isr function, there is HW specific code in this file but there is no way to include a header file that defines the SCB etc. This PR adds a way to include a header file so it is possible to make this file compile without local changes.
=> porting/npl/freertos: Add way of including HW specific header

nimble/host/src/ble_gap.c
This change sets length field only if data is non NULL, else sets  length to zero.
Core 5.4, Vol 4, Part E, section 7.8.62 states 
"If Operation is not 0x03 or 0x04 and Advertising_Data_Length is zero, then the Controller shall return the error code Invalid HCI Command Parameters (0x12).."
Current code sets length to size of data. However, to validate above, need to send 0 length . So calculate length only if data is present.
=>    nimble/host: Set length correctly in perdioic_set_adv_data

nimble/host/src/ble_uuid.c
hex2val returns BLE_HS_EINVAL on error which is positive value. This could result in UUID conversion errors as hex2bin is used by ble_uuid_from_str.
This was also causing build error with GCC 9:
repos/apache-mynewt-nimble/nimble/host/src/ble_uuid.c:76:28: error:
'tmp_val' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
76 |         bin[len] = tmp_val << 4;
|                    ~~~~~~~~^~~~
cc1: all warnings being treated as errors
=> nimble/host: Fix not catching conversion error in hex2bin

.github/workflows/build_cc_target.yml
This will help make sure we build correctly with more GCC version.
=> ci: Add workflow for testing various GCC versions

nimble/host/src/ble_gap.c, nimble/host/src/ble_store_util.c, nimble/host/store/config/src/ble_store_config.c, nimble/host/store/ram/src/ble_store_ram.c
This MR address the issue of code compilation warnings if Max bonds or Mac CCCDs is set to 0. Current code assumes that these values will never be 0.
=> Fix compilation issue when Max Bonds or CCCD is set as 0

apps/bttester/src/btp/btp_gap.h, apps/bttester/src/btp_gap.c
GCC 13 is complaining about zero elemen array that is not at the end of structure.
Error: repos/apache-mynewt-nimble/apps/bttester/src/btp_gap.c:
In function 'start_advertising':
repos/apache-mynewt-nimble/apps/bttester/src/btp_gap.c:467:29:
error: array subscript 514 is outside the bounds of an interior
zero-length array 'const uint8_t[0]' {aka 'const unsigned char[]'}
[-Werror=zero-length-bounds]
467 |     addr_type = cp->adv_data[cp->adv_data_len +
|                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
468 |                              cp->scan_rsp_len +
|                              ~~~~~~~~~~~~~~~~~~
469 |                              sizeof(duration)];
|                              ~~~~~~~~~~~~~~~~~
In file included from repos/apache-mynewt-nimble/apps/bttester/src/btp/btp.h:31,
from …
=> apps/bttester: Fix compilation with GCC 13

nimble/host/include/host/ble_sm.h, nimble/host/src/ble_sm.c, nimble/host/src/ble_sm_alg.c, nimble/host/src/ble_sm_priv.h, nimble/host/syscfg.yml, nimble/host/test/src/ble_sm_test.c, nimble/host/test/syscfg.yml
This adds functions and algorithms to encrypt and decrypt SIRK from Coordinated Set Identification Service.
This also adds API to resolve RSI. Application can use it to find devices that are part of Coordinated Set.
=> host/sm: Add CSIS SIRK encryption

nimble/host/src/ble_gap.c
This PR adds support to send Power control related events in the registered callback.
Till now, event was posted only to registered listeners. Some user, may be interested in getting events in a single registered callback
=> nimble/host: Add support to send power control event in registered callback

nimble/controller/include/controller/ble_ll_adv.h, nimble/controller/include/controller/ble_ll_sched.h, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_iso_big.c, nimble/controller/src/ble_ll_sched.c
This improves BIG scheduling in case periodic advertising interval is an integer multiple of ISO interval. In such case placing BIG event directly before periodic advertising event makes sure both won't overlap even if periodic advertising data changes in future.
Note that there may still be conflicts with other instances and this patch doesn't resolve that.
=> nimble/ll: Improve scheduling of 1st BIG event

apps/bttester/syscfg.yml
=> apps/bttester: enable EATT by default

apps/btshell/src/cmd.c, apps/bttester/src/btp_gap.c, apps/ext_advertiser/src/main.c, nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c
1. Added periodic adv enhancements(adi support) in Bluetooth spec 5.3
2. Current APIs don't have a way to add the parameters for periodic adv commands. So, modified the APIs wherever necessary.
=> Added periodic adv feature updates in ble 5.3

nimble/controller/include/controller/ble_ll_resolv.h, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_hci_vs.c, nimble/controller/src/ble_ll_resolv.c, nimble/controller/syscfg.yml, nimble/include/nimble/hci_common.h
This adds vendor-specific HCI command to set local IRK in controller.
Local IRK, if set, is used to generate local RPA in use cases where own address type was set to 0x02 or 0x03 but peer address is not added to resolving list. This for example allows to handle initiating connection to a new peer using RPA as our local address entirely in LL. Without that command it would be required for host to generate an RPA, set it as random address and connect using random address. This however doesn't work well with NimBLE host.
If no IRK is set (or set to all-zero), the controller behaves as usual which makes it safe to enable as it won't break anything.
=> nimble/ll: Add vs hci to set local IRK

nimble/controller/include/controller/ble_ll_isoal.h, nimble/controller/src/ble_ll_iso_big.c, nimble/controller/src/ble_ll_isoal.c, nimble/controller/syscfg.yml, nimble/include/nimble/hci_common.h
=> nimble/ll: BIG improvements

nimble/controller/pkg.yml, nimble/controller/src/ble_ll.c
This splits LL intiialization into two phases, one that initialize all LL internals and second that is called when LL side of transport is initialized. This makes sure that all internals are fully initialized before host sends any commands or LL sends any events (since HS side of transport is initialized before LL side) regardless of how much time pass between those HS and LL transport initialization.
=> nimble/ll: Split LL initialization

nimble/controller/src/ble_ll_hci.c
ISO can be used without connection (for example for Auracast). Then, g_ble_ll_data has no ACL members and compilation will fail.
=> controller/ble_ll_hci: fix ble_ll_hci_le_read_bufsize_v2 compilation

apps/bttester/src/btp/btp_mesh.h, apps/bttester/src/btp_mesh.c
BTP_MESH_INIT now only initialises Mesh. It expects additional field defining which composition data to use. For now it's parsed but ignored (we use always same composition data)
Introduced BTP_MESH_START command that enables Mesh advertising, as before it was in BTP_MESH_INIT. Command may be longer now, because static_auth can be 32 octets long. Additional field `static_auth_length` is ignored for now, as we support only 16 octet long auth.
=> apps/bttester: update Mesh commands

nimble/controller/syscfg.yml
BIG encryption takes additional space on stack, due to crypto functions.
=> controller: increase BLE_LL_STACK_SIZE for LE Audio Broadcast

nimble/controller/src/ble_ll_sched.c
BLE_LL_SCHED_TYPE_PERIODIC does not require BLE_LL_CFG_FEAT_LL_EXT_ADV.
=> ll/ble_ll_sched: fix preprocessor directives in ble_ll_sched_preempt

nimble/host/include/host/ble_gatt.h, nimble/host/services/gatt/src/ble_svc_gatt.c, nimble/host/src/ble_gatts.c
1. Fix read on client-supported features. 
2. Read cannot return the local client-supported features, it should return the client-supported features for the reading connection. (This change is needed for PTS).
=> nimble/gatts: Modify client supported features READ

nimble/host/include/host/ble_att.h, nimble/host/src/ble_gatt_priv.h, nimble/host/src/ble_gatts.c
Add Reserved For Future use bits check(needed for PTS)
=> nimble/gatts: Add check for RFU bits

porting/examples/linux/main.c, porting/examples/linux_blemesh/main.c, porting/examples/nuttx/main.c
Since HCI socket was initialized by `ble_transport_ll_init` in LL side,
we should remove `ble_hci_sock_init` from example apps.
Fixes：https://github.com/apache/mynewt-nimble/issues/1669
=> porting/linux: fix ble_hci_sock_init assertion

nimble/host/src/ble_gatts.c
This function would write pass conn->bhc_gatt_svr.peer_cl_sup_feat buffer. Since supported features are likely to be small (currently only 3 bits are defined) lets keep this simple and just make local copy before validation.
=> nimble/host: Fix possible overflow in ble_gatts_peer_cl_sup_feat_update

nimble/controller/src/ble_ll_ctrl.c
The instant for PHY update was calculated at the time PDU was enqueued in connsm. This caused new PHY to be always applied at instant regardless if PDU was even dequeued for tx, e.g. in case there encryption procedure pending. This could result in connection being dropped.
Currently we calculate instant when PDU is dequeued to make sure this is the next PDU to be sent and thus instant is valid.
=> nimble/ll: Fix PHY update instant calculation

porting/examples/linux/README.md
Readme was using very old (dead) link to BLE guide.
=> porting/linux: Fix link in README

nimble/host/include/host/ble_gap.h, nimble/host/services/auracast/src/ble_svc_auracast.c, nimble/host/src/ble_gap.c
All public GAP API functions shall return non-negative error codes. Now, function fills out pointer with found advertising instance and returns correct error code.
=> nimble/host: ble_gap_adv_get_free_instance shall return non-negative value

nimble/controller/src/ble_ll_ctrl.c, nimble/host/include/host/ble_gatt.h, nimble/host/services/gatt/src/ble_svc_gatt.c, nimble/host/src/ble_gatt_priv.h
This should be only for internal use. Return ATT error in ble_svc_gatt_cl_sup_feat_access, as ble_gatts_peer_cl_sup_feat_update returns host one.
=> nimble/host: move ble_gatts_peer_cl_sup_feat_update to private API

.github/workflows/build_cc_target.yml
This will test code with latest version of ARM GCC.
=> ci: Add GCC 13.2 to compilers test build workflow

nimble/host/include/host/ble_hs_log.h
Adds missing macro documentation (BLE_NPL_LOG_MODULE). Adds minor formatting improvements.
=> host/hs_log: Amend doxygen comments in the header file

nimble/host/src/ble_hs_conn.c
We don't need to have double loop and lock-unlock host lock when issuing disconnect. ble_gap_terminate_with_conn() can be used to disconnect and it can be called with already provided conn object under host lock.
=> nimble/host: Fix disconnect on host connection timeout

nimble/host/include/host/ble_iso.h
ble_gap_rx_create_big_complete and ble_gap_rx_terminate_big_complete are a leftover from initial implementation and shall be removed. Correct, implemented funcions are ble_iso_rx_create_big_complete and ble_iso_rx_terminate_big_completem, in private API
=> host/ble_iso.h: remove unused functions

nimble/host/include/host/ble_audio_broadcast.h
Adds missing structures and functions documentation. Corrects usage of 'param' tags.
=> host/audio_broadcast: Amend doxygen comments in the header file

.github/workflows/compliance_check.yml
RAT 0.16.1 was released so we no longer need to use snapshots for SPDX support.
=> ci: Use latest RAT release

nimble/drivers/native/src/ble_phy.c
This fixes compilation error caused by value assignment to undefined structure aux_data member. Introduced in 4e58b2724.
=> nimble/phy: Fix compilation error

nimble/host/src/ble_gap.c
IRK of the peer might not be present on the resolving list, but we still should be able to remove that entry.
Previously this operation would produce an error, and removal was unsuccessful.
=> Fix remove from resolving list issue

apps/btshell/src/main.c
This fixes format specifer for printing CoC channel pointer.
=> apps/btshell: Fix print format specifier

nimble/host/include/host/ble_audio_broadcast.h
Added clarification for `big_params` pointer in
`ble_broadcast_create_params`.
=> host/ble_audio_broadcast: add clarification for big_params pointer

nimble/drivers/native/src/ble_phy.c
This fixes unit test compilation error caused by missing ble_phy_tifs_txtx_set() and ble_phy_encrypt_header_mask_set() function stubs used by ble_ll_iso_big.c and ble_ll_isoal.c.
=> nimble/drivers/native: Add missing function stubs

nimble/controller/syscfg.yml
To support encrypting/decrypting broadcasts, LL Encryption shall be enabled by BLE_LL_ISO_BROADCASTER.
=> nimble/controller: Enable LL encryption if BLE_LL_ISO_BROADCASTER

nimble/host/include/host/ble_audio_common.h
Adds missing structures and macros documentation.
Adds minor corrections to existing entries.
=> host/audio_common: Add doxygen comments in the header file

apps/btshell/src/btshell.h, apps/btshell/src/cmd.c, apps/btshell/src/cmd_iso.c, apps/btshell/src/cmd_iso.h, apps/btshell/src/main.c, nimble/controller/syscfg.yml, nimble/host/audio/targets/btshell_native/pkg.yml, nimble/host/audio/targets/btshell_native/syscfg.yml, nimble/host/audio/targets/btshell_native/target.yml, nimble/host/include/host/ble_iso.h, nimble/host/src/ble_hs.c, nimble/host/src/ble_hs_hci_evt.c, nimble/host/src/ble_hs_startup.c, nimble/host/src/ble_iso.c, nimble/host/src/ble_iso_priv.h, nimble/include/nimble/hci_common.h, nimble/syscfg.yml, nimble/transport/socket/src/ble_hci_socket.c
This adds ISO Rx datapath and along with Broadcast Sink ISO API
and implementation.
This also extends btshell application with Broadcast ISO related commands.
Depends on: https://github.com/apache/mynewt-nimble/pull/1700
=> nimble/iso: Add ISO Rx datapath and extend ISO Broadcast API

nimble/host/audio/include/host/audio/ble_audio.h, nimble/host/audio/pkg.yml, nimble/host/audio/src/ble_audio.c, nimble/host/audio/src/ble_audio_priv.h, nimble/host/audio/syscfg.yml, nimble/host/audio/test/pkg.yml, nimble/host/audio/test/src/ble_audio_test.c, nimble/host/audio/test/src/testcases/ble_audio_base_parse_test.c, nimble/host/audio/test/src/testcases/ble_audio_listener_register_test.c, nimble/host/audio/test/syscfg.yml, nimble/host/include/host/ble_audio_common.h, nimble/host/services/auracast/src/ble_svc_auracast.c
This adds dedicated event listener for LE Audio events and BASE parser implementation along with unit tests.
=> nimble/audio: Add LE Audio event listener and BASE parser

nimble/host/include/host/ble_iso.h
Adds missing structures and functions documentation.
=> host/iso: Add doxygen comments in the header file

nimble/host/src/ble_hs.c
BLE_ISO defines ISO as whole, but we RX iso data only when device is broadcast sink.
=> host/ble_hs: call ble_iso_rx_data if BLE_ISO_BROADCAST_SINK

nimble/host/src/ble_att_svr.c
This commit applies valid response (Request Not Supported) when mtu exchange is requested over EATT.
=> nimble/host: Fix invalid response for mtu exchange request

ext/libsamplerate/pkg.yml
Debug build pulls assert.h and nrfx, in which PACKAGE define isi pulled from libsamplerate/serc/config.h. This is not correct behavior and these defines are not correlated. Library should be always build without asserts, circumventing the issue.
Cleaned up duplicated cflags in pkg.yml.
=> ext/libsamplerate: always build with DNDEBUG flag

nimble/host/src/ble_att_cmd.c
If ble_hs_misc_conn_chan_find_reqd() failed function would exit with HS lock locked.
=> nimble/host: Fix possible deadlock in ble_att_tx

nimble/controller/include/controller/ble_ll_adv.h, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_sched.c
some advertising fixes:
- try to reschedule adv event again if preempted instead of just dropping it
- fix sync packet offset calculation in syncinfo
=> nimble/ll: Advertising fixes

apps/bttester/src/btp_gap.c
This shoudl allow to run GAP and GATT tests with BLE_EXT_ADV enabled.
=> apps/bttester: Fix use of extended advertising interface

nimble/controller/src/ble_ll_sync.c
acad_len in ble_ll_sync_rx_pkt_in is filled in ble_ll_sync_parse_ext_hdr and later accessed in ble_ll_sync_check_acad. There is a possibility that extended advertising header is missing data containing acad, and it will not get filled, leaving it uninitialised.
This fixes compilation warning:
```
Error: In function 'ble_ll_sync_check_acad',
inlined from 'ble_ll_sync_rx_pkt_in' at repos/apache-mynewt-nimble/nimble/controller/src/ble_ll_sync.c:1207:18:
repos/apache-mynewt-nimble/nimble/controller/src/ble_ll_sync.c:1064:21: error: 'acad_len' may be used uninitialized [-Werror=maybe-uninitialized]
1064 |     while (acad_len > 2) {
|            ~~~~~~~~~^~~
repos/apache-mynewt-nimble/nimble/controller/src/ble_ll_sync.c: In function 'ble_ll_sync_rx_pkt_in': …
```
=> controller/ble_ll_sync.c: acad_len potentially uninitialised

nimble/host/audio/src/ble_audio.c
data->success was set to false at every entry to the funcion. That made the valid advertising payload fail after parsing
BLE_BROADCAST_PUB_ANNOUNCEMENT_SVC_UUID - final break in block was reached but the success set in parsing
BLE_BROADCAST_AUDIO_ANNOUNCEMENT_SVC_UUID was cleared.
=> host/ble_audio.c: fix ble_audio_adv_parse_broadcast_announcement

nimble/host/include/host/ble_gap.h
Added to the description condition when the Periodic Sync actually happens.
=> host/ble_gap.h: Extend description of ble_gap_periodic_adv_sync_create

nimble/host/src/ble_iso.c
Freeing memory back to BIS pool in loop while changing removing ISO connections from list lead to memory leak. Now, memory is freed in separate loop.
=> host/audio/ble_iso.c: fix deallocation of BIS

nimble/host/audio/services/pacs/src/ble_audio_svc_pacs.c
Fix for incorrect  PACS characteristic sending notification after changing it's state.
=> Fix incorrect PACS characteristic notification

nimble/host/audio/services/pacs/src/ble_audio_svc_pacs.c
=> host/audio/pacs: fix possible NULL dereference

nimble/host/store/config/src/ble_store_config.c
This should fix compilation error when -O2 optimization is enabled. GCC incorrectly detects problem.
This change adds asserts that convinces GCC that pre-condition will not result in accessing memory out-of-bounds.
This also changes one condition that also contributes to make GCC convinced that pre-condition are met.
Error: In function 'ble_store_config_delete_obj',
inlined from 'ble_store_config_delete_cccd' at repos/apache-mynewt-nimble/nimble/host/store/config/src/ble_store_config.c:380:10,
inlined from 'ble_store_config_delete' at repos/apache-mynewt-nimble/nimble/host/store/config/src/ble_store_config.c:542:14:
repos/apache-mynewt-nimble/nimble/host/store/config/src/ble_store_config.c:193:9: error: 'memmove' offset [16, 31] is out of the bounds [0, 16] of object …
=> nimble/host: Fix compilation error in ble_store_config.c

apps/auracast_usb/include/tusb_config.h, apps/auracast_usb/include/usb_audio.h, apps/auracast_usb/pkg.yml, apps/auracast_usb/src/app_priv.h, apps/auracast_usb/src/audio_usb.c, apps/auracast_usb/src/main.c, apps/auracast_usb/src/usb_desc.c, apps/auracast_usb/syscfg.usb.yml, apps/auracast_usb/syscfg.yml, ext/libsamplerate/pkg.yml, ext/libsamplerate/src/config.h, ext/libsamplerate/syscfg.yml, targets/auracast_usb/nrf5340-mcu.ld, targets/auracast_usb/nrf5340.ld, targets/auracast_usb/pkg.yml, targets/auracast_usb/syscfg.yml, targets/auracast_usb/target.yml
This adds sample that acts as USB sound device. Audio signal is coded using LC3 and broadacasted using Auracast package.
=> apps: add Auracast USB sample with LC3 codec

nimble/host/src/ble_l2cap_coc.c
Two functions: `ble_l2cap_coc_continue_tx` and `ble_l2cap_coc_recv_ready` can be reached from other task than host, for example separate thread running in application, by calling `ble_l2cap_recv_ready` or `ble_l2cap_send`. Because pointer to chan passed into  these functions may be outdated (connection is being terminated by host) this will lead to either:
- triggering BLE_HS_DBG_ASSERT(conn != NULL) in ble_hs_conn_find_assert
- dereferencing NULL pointer to conn, after ble_hs_conn_find_assert returns NULL (case with disabled BLE_HS_DEBUG) These two cases shall not cause assert, and should be prepared for chan not existing anymore. Now, BLE_HS_ENOTCONN is returned if connection no longer exists.
=> host/ble_l2cap_coc: fix possible race condition in L2CAP COC

nimble/host/audio/include/audio/ble_audio.h, nimble/host/audio/services/bass/include/services/bass/ble_audio_svc_bass.h, nimble/host/audio/services/bass/pkg.yml, nimble/host/audio/services/bass/src/ble_audio_svc_bass.c, nimble/host/audio/services/bass/syscfg.yml, nimble/host/include/host/ble_att.h
=> nimble/host: Add Broadcast Audio Scan Service

apps/btshell/src/cmd_iso.c, nimble/host/include/host/ble_iso.h, nimble/host/src/ble_iso.c, nimble/include/nimble/hci_common.h
This moves the ISO Rx callback to be provided by application as Setup ISO Data Path function parameter, as the callback will be used only for HCI data path, thus there is no point to require the callback when the broadcast sync is created.
=> nimble: iso: Move Rx callback param to Setup ISO Data Path command

nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c
Added an API to retrieve size of whitelist entries controller supports.
=> nimble/host: Add API to retrieve the size of the controller's white list

nimble/transport/socket/src/ble_hci_socket.c
Hi,
This patch fixes host stack compilation with `BLE_SOCK_USE_TCP=1`. Error message below
```
/usr/bin/ld: libnimble.a(ble_hci_socket.c.o): in function `ble_hci_trans_ll_evt_tx':
/yoyo/mynewt-nimble/nimble/transport/socket/src/ble_hci_socket.c:730: undefined reference to `ble_hci_sock_cmdevt_tx'
/usr/bin/ld: libnimble.a(ble_hci_socket.c.o): in function `ble_hci_trans_ll_acl_tx':
/yoyo/mynewt-nimble/nimble/transport/socket/src/ble_hci_socket.c:744: undefined reference to `ble_hci_sock_acl_tx'
/usr/bin/ld: libnimble.a(ble_hci_socket.c.o): in function `ble_hci_trans_hs_cmd_tx':
/yoyo/mynewt-nimble/nimble/transport/socket/src/ble_hci_socket.c:759: undefined reference to `ble_hci_sock_cmdevt_tx'
/usr/bin/ld: libnimble.a(ble_hci_socket.c.o): in function `ble_hci_trans_hs_acl_tx': …
```
=> nimble/transport: Fix compilation with TCP socket transport

nimble/host/src/ble_gap.c
ble_gap_slave_extract_cb not only gets information of callback but also resets the slave advertising state. 
When invoked from ble_gap_adv_finished, this behaviour is ok , but in case of invocation from ble_gap_rx_scan_req_rcvd , the current code stops advertising.  If scan request notification has been enabled, the host may want to be updated about scan request. But scanning procedure should still go on. 
Current code, attempts to not reset the slave advertising state inside ble_gap_slave_extract_cb but moves it explicitly after adv has finished.
=> nimble/host: Avoid slave instance reset inside extract_cb

nimble/transport/uart_ll/src/hci_uart.c
Change `BLE_TRANSPORT_UART_*` in `hci_uart.c` to `BLE_TRANSPORT_UART_LL_*` to match definitions in `syscfg.yml`.
`uart_ll` was added by 80ef459c48dd2e938789013da1222438ffa2bf92 (https://github.com/apache/mynewt-nimble/pull/1399) as a copy of existing `uart` transport. `_LL` was added to `BLE_TRANSPORT_UART_*` definitions in `syscfg.yml`, but not in the `hci_uart.c` file.
Fixes https://github.com/apache/mynewt-nimble/issues/1438
=> nimble/transport: Fix syscfg definition names for uart_ll transport

nimble/host/src/ble_sm.c
This fixes invalid conn handle check in SM. The handle 0 is valid connection handle.
=> nimble/host: Fix invalid connection handle check in SM

nimble/host/src/ble_gap.c
Configured advertisign instance is required in order to set advertising data when extended advertising HCI is used. Since when legacy PDU are in use we can set both AD and SCAN_RSP we can easily pre-configure selected instance just for this purpose and re-configure it before starting advertising without affecting set AD/SCAN_RSP.
=> nimble/host: Fix legacy advertising API with EXT_ADV enabled

apps/bttester/src/btp_gatt_cl.c, nimble/host/src/ble_gattc.c
- Add early exit in read_var_cb for readabilty 
- Apply correct value when using memset to fill attr array in ble_gattc_read_mult_cb_var. Fixes GATT/CL/GAR/BI-13-C, GATT/CL/GAR/BI-36-C, GATT/CL/GAR/BI-38-C, GATT/CL/GAR/BI-42-C, GATT/CL/GAR/BI-44-C, GATT/CL/GAR/BV-05-C
=> nimble/host: Fix invalid memset in ble_gattc_read_mult_cb_var

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll_ctrl.c
This fixes 2 issues in encrpytion pause/restart procedure (i.e. key refresh) initiated in central role:
1. We transition to "paused" encryption state when LL_PAUSE_ENC_RSP is txd, but that is done after we try to enqueue LL_ENC_REQ. This means LL_ENC_REQ is put at the end of tx queue. By conicidence this makes order of PDUs correct when there's only LL_PAUSE_ENC_RSP on tx queue, but it fails if there was an ACL packet already queued. In such case LL_ENC_REQ is queued after that ACL packet which means neither will be sent - ACL packet cannot be sent because we have no encryption, LL_ENC_REQ cannot be sent because there's ACL packet in front.
2. We do not check if LL_ENC_REQ was properly queued (i.e. if mbuf was allocated for PDU) so it may happen that LL_ENC_REQ will never be queued.
In …
=> nimble/ll: Fix encryption pause/restart procedure

porting/npl/nuttx/include/nimble/nimble_npl_os_log.h
porting/npl/nuttx/include/nimble/nimble_npl_os_log.h: fix gcc14 error
> error: implicit declaration of function 'vprintf' [-Wimplicit-function-declaration]
>   32 |             vprintf(fmt, args);
GCC14 has a more restrictive warning policy and treats some warnings as errors, which breaks compilation for NuttX
EDIT: it looks like the problem also occurs for older GCC versions, as reported by NuttX CI: https://github.com/apache/nuttx-apps/actions/runs/9483234519/job/26130011374#step:7:368
=> porting/npl/nuttx/include/nimble/nimble_npl_os_log.h: fix gcc14 error

.github/workflows/build_ports.yml
Adds a step to the CI workflow for checking the build of Nuttx master branch.
=> ci: Build Nuttx port

nimble/transport/socket/src/ble_hci_socket.c
Add support for sending ISO data on native.
=> nimble/transport/socket: Add ISO Tx transport support

nimble/include/nimble/hci_common.h
For LE Read Advertising Physical Channel Tx Power command , different version of BLE specification have updated the return values for Tx Power level. 
Currently (spec 5.2 onwards) the supported values are from (-127) to (20). 
Latest values as per Spec ver 5.4 , Vol 4, Part E, section 7.8.6 has range specified. 
Update the min / max macros to reflect the same
=> nimble/host: Modify Advertising Tx power levels

nimble/controller/src/ble_ll_iso_big.c
Controller now uses RTN parameter to include retransmissions in BIG event. This applies only to IRC for now, pretransmissions are not included.
=> nimble/ll: Use retransmissions for BIG Create

nimble/drivers/nrf5x/src/ble_phy.c
Delay for event END was always included in tx-tx transition calculations which resulted in invalid calculations for tx-tx transition anchored at packet start. This fixes the issue and also fixes timing for event ADDRESS since it seems to be different that the one for END event.
=> nimble/phy: Fix tx-tx transition timing

nimble/controller/src/ble_ll_isoal.c
LLID=1 should be only used for empty PDUs that are sent as padding for SDUs that are too short.
=> nimble/ll: Fix LLID for empty BIS PDUs

nimble/host/src/ble_gattc.c
If we sent the same request to two different peers at exactly the same time, it was possible that responses could be matched with invalid procedures.
=> nimble/host: Fix matching responses to ATT procedures

nimble/controller/src/ble_ll_iso_big.c
The anchor base for BIG events was reset every 30mins to avoid overflow in offset calculations which could happen after more than 60mins of streaming.
However, as it turns out anchor offset wraps-around much earlier than that after just ~10m55s (at 10ms iso interval) so we should better take care of anchor offset instead of offset_us.
=> nimble/ll: Fix BIG anchor offset overflow

nimble/transport/include/nimble/transport.h, nimble/transport/nrf5340/src/nrf5340_ble_hci.c, nimble/transport/nrf5340/syscfg.yml, nimble/transport/src/rx_task.c, nimble/transport/syscfg.monitor.yml, nimble/transport/syscfg.yml
This adds common task for implementing HCI RX. Any transport can simply
register its own function for RX that will be run in separate task
whenever triggered by dedicated API. This for example allows to easily
implement handling HCI RX in a task instead of in an interrupt since
handling RX in an interrupt doesn't work well with monitor enabled.
If selected transport doesn't register its function, all rx_task code
will be compiled out since there won't be any references to that code.
=> nimble/transport: Add common HCI RX task

nimble/transport/nrf5340/src/nrf5340_ble_hci.c, nimble/transport/nrf5340/syscfg.yml, nimble/transport/src/rx_task.c, nimble/transport/syscfg.yml
Remove separate syscfg to enable RX task from nrf5340 transport package. RX task is now enabled if RX task stack size is set to a valid value.
RX task priority should not be set to default value to avoid conflicts with other task priorities if RX task is not used (this is always verified by newt). Since empty value is not a valid priority we should better only define that setting if RX task is enabled.
=> nimble/transport: Fix build with RX task

nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Modify loop expressions to use ARRAY_SIZE macro instead of sizeof in BASS.
=> nimble/audio: Change sizeof to ARRAY_SIZE in BASS

nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Fix event type in ble_audio_event structure.
Modify data for use with new mbuf.
Add characteristic value in receive state.
Remove goto pointing to goto itself.
=> nimble/audio/bass: Modify remove source operation

nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Add data length checks to remote scan operations. Now any data coming with remote scan start/stop will result in instant ATT error.
=> nimble/audio/bass: Add data length check in BASS remote scan

nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Modify BASS control point write access in a way that it would use proper mbuf for holding incoming data.
Fix handler check from simple bool comparison to ensuring that it's not NULL.
=> nimble/audio: Modify BASS control point write access.

nimble/transport/nrf5340/src/nrf5340_ble_hci.c
The HCI transport is initialized after LL task is initialized, but the IPC itself is initialized before LL task. If host on appcore starts before HCI transport is initialized on netcore, it can put HCI Reset in IPC shm before we can receive it and handle. This causes host to send 2nd HCI Reset which triggers handling of data in IPC shm and will fail because we cannot handle 2 HCI commands at the same time (i.e. 2x HCI Reset).
This fixes the problem by triggering read from IPC shm just after HCI transport is initialized so we can handle command that was sent there before we were ready to receive it.
=> nimble/transport: Fix race in nrf5340 IPC transport

apps/auracast/src/main.c, apps/auracast/syscfg.yml
This fixes auracast native build by disabling GPIO button functionality.
=> apps/auracast: Make the code compile on native target

porting/npl/linux/src/os_callout.c
`ble_npl_callout.c_active` is not reset after callout is executed, so only the first callout fires and subsequent are not scheduled at all.
Fixes https://github.com/apache/mynewt-nimble/issues/1771
=> porting/npl/linux: Fix stuck callouts

porting/npl/linux/src/os_sem.c
It's been observed that `sem_timedwait()` can return `EINTR` even if `sigaction()` specified `SA_RESTART`.
Not sure what the deal with that is but handling it is simple enough.
=> porting/npl/linux: Handle EINTR from sem_timedwait

nimble/host/include/host/ble_gap.h, nimble/host/src/ble_gap.c, nimble/host/src/ble_hs_hci_priv.h, nimble/host/src/ble_hs_startup.c, nimble/include/nimble/hci_common.h
BLE spec version 5.4 introduced support for host to pass primary and secondary phy options in set extended advertising parameters. For this a new HCI command "HCI_LE_Set_Extended_Advertising_Parameters v[2] " with OCF 0x007F got introduced. 
This patch adds support in host for this HCI command.
=> nimble/host: Add support for ext adv param v2 HCI command

nimble/host/src/ble_gap.c
This eliminates "declared but not used" warnings.
=> nimble/host: Fix build for extended scan

nimble/drivers/fem/sky66405/include/sky66405/sky66405.h, nimble/drivers/fem/sky66405/pkg.yml, nimble/drivers/fem/sky66405/src/sky66405.c, nimble/drivers/fem/sky66405/syscfg.yml
This adds driver for SKY66405 FEM.
The bypass function is only supported using dedicated pin (CPS). Enabling bypass by setting both CTX and CRX to high state is not supported due to limitation in FEM API.
=> nimble/drivers: Add driver for SKY66405 FEM

nimble/controller/src/ble_ll_scan.c
We should not reply on ADV_NONCONN_IND and SCAN_IND as initiator - those are not connectable so we'll just get connection failed to be established error.
=> nimble/ll: Fix non-connectable PDUs handling for initiator

nimble/host/src/ble_gap.c
This fixes L2CAP update request event handling to be the same a connection update request as described in documentation.
The copy of requested parameters is passed as peer_params while the original param struct is passed as self_params so application can update these if needed.
=> nimble/host: Fix L2CAP update request event

nimble/host/src/ble_gap.c
Was getting duplicate definitions of SET_BIT when compiling for an STM32F4 device.
=> nimble/host/src/ble_gap.c:  undefined SET_BIT before defining it.

nimble/host/src/ble_eatt.c
Data packets sent over eatt chan weren't correctly truncated. Data packet is now adjusted to peer device's MTU for the channel.
Fixes various GATT/SR test cases that verify support for Read Long Characteristic Value Requests, Multiple Read Characteristic Value Requests etc.
https://github.com/apache/mynewt-nimble/issues/1800 related
=> nimble/host: Truncate data in ble_eatt_tx

nimble/host/audio/src/ble_audio_scan_delegator.c
This commit changes subgroups filed in assert
used in operation handler in scan delegator.
Now proper defined array size is used.
=> nimble/audio: Use proper array size in assert within scan delegator.

apps/auracast_usb/syscfg.yml
=> apps/auracast_usb: Fix default value for BIG PHY

nimble/host/src/ble_hs_hci_evt.c
Advertising instance is used for indexing slave state array. Since instance is provided by host invalid handle in event means there is bug in controller.
=> nimble/host: Validate advertising instance before parsing event

nimble/controller/src/ble_ll_iso_big.c
RTN is number of retransmissions onlt so IRC=RTN+1.
=> nimble/ll: Fix RTN handling in HCI BIG Create

nimble/controller/include/controller/ble_ll_adv.h, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_iso_big.c
This modifies padv event start time calculations to use single event
start time as anchor and calculate subsequent event start times as an
offset from that event.
This virtually removes drift due to rounding errors and avoids relative
drift of padv vs. BIG events.
=> nimble/ll: Fix periodic advertising event timing

nimble/controller/include/controller/ble_ll_adv.h, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_hci.c, nimble/controller/src/ble_ll_hci_supp_cmd.c, nimble/host/src/ble_gap.c, nimble/include/nimble/hci_common.h
This adds second version of Set Extended
Advertising Parameters command (7.8.53)
Introduced in Core Specification v5.4.
=> nimble/ll: Add set ext adv params v2 command

nimble/host/src/ble_gattc.c
We can stop characteristics discovery as soon as there are less than 2 attributes left. This means if last characteristic has descriptor (e.g. CCC) we will save single ATT_READ_BY_TYPE_REQ/RSP transaction.
As a side-effect we also resume discovery starting from the next handle after last characteristic value handle instead of characteristic declaration handle, but this is ok since there cannot be any atrtibutes (so also characteristic declarations) between characteristic declaration and characteristic value.
=> nimble/host: Optimize characteristics discovery

nimble/host/src/ble_hs_conn.c
We need to free all mbufs enqueued on ATT queue when connection is freed, otherwise we may leak mbufs.
=> nimble/host: Clear ATT queue on conn_free

nimble/controller/src/ble_ll_hci_ev.c
This allows app on host to simply print the contents of event.
=> nimble/ll: Null-terminate string in vs_printf HCI event

nimble/host/include/host/ble_gatt.h, nimble/host/src/ble_gatts.c
To obtain an attribute value when the attribute size is greater than configured MTU long attribute read procedure could be used.
A client sends consecutive `ATT_READ_BLOB_REQ` requests (passing along an offset) to consume the attribute value. The offset is used internally in the nimble stack but is not passed to a user provided access callback in a GATT characteristic description. This callback is called the same number of times as the number of blob requests, but it's not possible to say whether it's a first request (or maybe just `ATT_READ_REQ`) or consecutive request.
The provided offset could indicate this situation to the app developer. However, Core Spec 5.4 Vol 3 Part F 3.4.4.5 notes:
> Note: The value of a Long Attribute may change between the server receiving one …
=> Offset field in struct ble_gatt_access_ctxt as an indication of long attribute read

nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_iso_big.c
Offset calculation in BIGInfo assumes BIG event start time is always after AUX_SYNC_IND since BIG should be advanced to next event by the time AUX_SYNC_IND is sent. However, if AUX_SYNC_IND is scheduled close to BIG event this may not happend and thus calculated offset is invalid.
This makes sure that we always use BIG event after AUX_SYNC_IND to calculate offset.
=> nimble/ll: Fix offset calculation in BIGInfo

nimble/controller/include/controller/ble_ll_conn.h, nimble/controller/src/ble_ll_adv.c, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_sync.c
This simplifies calculation of SyncInfo used in AUX_ADV_IND and LL_PERIODIC_SYNC_IND to use the same code in both cases.
In case of LL Control PDU we do not "rewind" connsm to find proper connection event but instead "advance" padv event the same way as it was done for AUX_ADV_IND PDU.
=> nimble/ll: Simplify SyncInfo calculation

nimble/host/audio/services/bass/include/services/bass/ble_audio_svc_bass.h, nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Modify add source with new mbuf data style format. Add BIS sync information to receive state.
Fix memcpy wrong field format from address.
Move check_bis_sync up, so add source can use it.
Add checks for address type.
Add checks for advertising sid.
Add pa_sync_state and num of subgroups to receive state.
=> nimble/audio/bass: Modify add source operation in BASS

nimble/host/audio/services/bass/include/services/bass/ble_audio_svc_bass.h, nimble/host/audio/services/bass/src/ble_audio_svc_bass.c, nimble/host/audio/src/ble_audio_scan_delegator.c
Add subgroups info for modify source operation. Now metadata field can be handled in scan delegator during modify procedure.
=> nimble/audio: Add subgroups information for modify operation

nimble/controller/src/ble_ll_conn_hci.c
Minor fix. We should set conn_handle in the
command response buffer before returning.
=> nimble/ll: Set handle in cmd_resp before return

nimble/host/src/ble_att.c, nimble/host/src/ble_att_cmd_priv.h, nimble/host/src/ble_eatt.c
Att opcode check caused l2cap disconnection when opcode included in received data was write command which is supported and can be used on eatt. Also, the comment seemed irrelevant. Fixes GATT/SR/GAW/BV-01-C
=> nimble/host: add eatt opcode check in ble_eatt_l2cap_event_fn

.github/workflows/newt_test_all.yml
We properly support 64bit in native target now so those can be re-enabled.
=> ci: Enable newt test on Mac

nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
Remove unnecessary buffer from operation.
Pass proper buffer to handler.
=> Control point buffer fix

porting/nimble/src/os_mbuf.c
This fix msys allocation with multiple mpools. From upstream commit:
" When msys was configured with several mpools and one of the pools run out of buffers, os_mbuf_get() returned NULL even though other mpool did have buffers available.
Now search for suitable buffer checks if suitable pool is empty and if not search continues."
=> porting: Sync mbuf with latest core

porting/npl/linux/src/os_atomic.c
Simply define this before including any systema headers.
g -D_GNU_SOURCE  -o ../../../porting/npl/linux/src/os_atomic.o ../../
../porting/npl/linux/src/os_atomic.c
../../../porting/npl/linux/src/os_atomic.c:21:9: warning: "__USE_GNU" redefined
21 | #define __USE_GNU
|         ^~~~~~~~~
In file included from /usr/include/bits/libc-header-start.h:33,
from /usr/include/stdint.h:26,
from /usr/lib/gcc/x86_64-redhat-linux/14/include/stdint.h:9,
from ../../../porting/npl/linux/src/os_atomic.c:20:
/usr/include/features.h:409:10: note: this is the location of the previous definition
409 | # define __USE_GNU      1
|          ^~~~~~~~~
=> porting/linux: Fix warning about __USE_GNU redefinition

apps/bttester/pkg.yml, apps/bttester/src/btp/btp.h, apps/bttester/src/btp/btp_pacs.h, apps/bttester/src/btp/bttester.h, apps/bttester/src/btp_core.c, apps/bttester/src/btp_pacs.c, apps/bttester/syscfg.yml
Add support for Published Audio Capabilities Service in bttester application.
=> Add support for PACS autopts tests

nimble/host/src/ble_hs_hci_evt.c
Validate if HCI event received from controller has proper sizes before passing it to GAP event
=> nimble/host: Add Number Complete Packets event validation

nimble/host/audio/services/bass/src/ble_audio_svc_bass.c
This commit fixes logic for address
recognition in add_source operation
=> Fix condition in address recognition

nimble/controller/src/ble_ll_hci.c
We do not have extended features pages so remove bit from standard features and make HCI Read Extended Featuers fail on page>0.
=> nimble/ll: Fix extended features for fake dual mode

nimble/controller/src/ble_ll.c
The call to ble_ll_isoal_reset() is behind define, but include was not. Same for iso_big
=> nimble/ll: make includes config dependent

nimble/controller/src/ble_ll_conn.c
We should not attempt to initiate connection if there's not enough time left for connection req/rsp before next scheduling item, otherwise it may be corrupted since scheduler will forcibly disable phy before executing new item.
=> nimble/ll: Check scheduler before sending connection request

apps/bttester/src/uart_pipe.c, apps/bttester/syscfg.yml
uart_pipe.c from bttester app was using values copied directly from uart_console.c e.g. CONSOLE_UART_DEV, CONSOLE_UART_BAUD. This caused BTP malfunction when trying to receive logs over UART from bttester. BTTESTER_UART variables are now added to syscfg and applied in uart_pipe.c
=> apps: bttester: fix uart settings

nimble/controller/src/ble_ll_conn.c
If single CRC error is received we should always reply to allow other side to retransmit the packet.
If two consecutive CRC errors are received, we will close the connection event.
=> nimble/ll: Fix closing connection event on CRC error

nimble/controller/src/ble_ll_conn_hci.c, nimble/controller/src/ble_ll_ctrl.c
Interval should be clipped only if CSS is runtime enabled and not just compiled in.
=> nimble/ll: Fix connection  parameters update with CSS build in

nimble/host/src/ble_gattc.c
A wrong Host Error Code was used in ble_gattc.c file and caused compilation error. Fix it by replacing with the correct Host Error Code.
=> Fix wrong Host Error Code used in ble_gattc file

nimble/host/src/ble_gatts.c, porting/npl/riot/include/nimble/nimble_npl_os_log.h
This resolves the -Wformat-nonliteral warning by (which complains about non-literals used as printf formatters, unless the containing function itself is also printf style), and a stray leftover empty debug statement discovered by that warning: -Wformat-nonliteral is a bit of a false postive here because due to the level prefix, the empty printf is not *really* empty, but it is accurate enough in that it does not provide any valuable details.
---
This was found when building the latest nimble with RIOT, which has relatively strict warnings on – and while those are often disabled for projects that don't usually build with the strict warnings, since the debug header gets included in public headers, it spreads to many compilation units. Applying the attribute(format) is also in line with …
=> debug: Declare as printf-style, remove empty statement

nimble/host/src/ble_l2cap_coc.c
Use of undeclared min function causes build warning. Declare the min and max function in file ble_l2cap_coc.c
=> Fix a build warning caused by using undeclared min function

nimble/host/store/config/src/ble_store_config.c
Use of undeclared ARRAY_SIZE macro causes build warning. Add include to "os/util.h" in ble_store_config.c file.
=> Fix a build warning caused by using undeclared ARRAY_SIZE macro

nimble/controller/include/controller/ble_ll_scan.h, nimble/controller/src/ble_ll_hci_vs.c, nimble/controller/src/ble_ll_scan.c, nimble/controller/syscfg.yml, nimble/include/nimble/hci_common.h
This allows to configure scanner to ignore either
legacy or extended packets. If scan is enabled
command returns command disallowed error.
=> nimble/ll: Add vs hci cmd with additional scan cfg

nimble/host/src/ble_sm.c
When BLE_SM_SC_ONLY is on during pairing request, the process might fail even though both SC is supported by the peer and the key size meet the requirements.
=> host: sm: secure connection only pairing might fail with no reason

nimble/include/nimble/hci_common.h, nimble/transport/common/hci_h4/src/hci_h4.c, nimble/transport/nrf5340/src/nrf5340_ble_hci.c
Length in ISO HCI packets is 14 bits.
=> nimble/transport: Fix ISO HCI length parsing

nimble/controller/src/ble_ll_scan.c
Local IRK, if set, is used to generate local RPA in use cases where own address type was set to 0x02 or 0x03 but peer address is not added to resolving list.
If no IRK is set (or set to all-zero), the controller uses NRPA.
This is already done for AUX_SCAN_REQ and legacy PDU was accidentally omitted in previous PR.
=> nimble/ll: Use RPA from global local IRK on active scan for legacy PDU

nimble/controller/src/ble_ll_adv.c
We should use padv interval value in ticks for calculations, not in HCI units...
=> nimble/ll: Fix padv interval check for scheduling

nimble/controller/include/controller/ble_ll_scan.h, nimble/controller/src/ble_ll_scan.c, nimble/controller/src/ble_ll_scan_aux.c, nimble/controller/syscfg.yml
This adds a syscfg to disable NRPA generation by LL in active scan. This allows host to specify own NRPA as a random address and use it instead of the one generated by LL.
Also this moves code to make SCAN_REQ/AUX_SCAN_REQ to common helper so we don't duplicate code.
=> nimble/ll: Make NRPA generation in active scan optional

nimble/controller/syscfg.yml
Intention was to default to 1 if privacy is enabled, not forcing privacy.
=> nimble/ll: Fix default value for BLE_LL_SCAN_ACTIVE_SCAN_NRPA

nimble/controller/src/ble_ll_scan_aux.c
This fixes condition to check if AUX_ADV_IND has both ADI and SyncInfo before passing it to sync code.
Invalid condition allowed that either ADI *or* SyncInfo is present in whch case the offset to SyncInfo in PDU was calculated incorrectly and the resulting sync sm used random data and thus failed.
=> nimble/ll: Fix sync check in aux

nimble/controller/src/ble_ll.c, nimble/controller/src/ble_ll_conn_hci.c, nimble/controller/src/ble_ll_conn_priv.h, nimble/controller/src/ble_ll_hci.c, nimble/controller/src/ble_ll_hci_supp_cmd.c
We don't need to support this command if there are no host-controllable
features present in LL.
=> nimble/ll: Fix supported HCI commands

Doxyfile
It looks like newer version of Doxygen has issues if no output is generated. Specify to generate HTML output in tmp folder.
=> ci: Fix doxygen checks

nimble/controller/src/ble_ll_iso_big.c
This fix merged in 890be280a3 was broken during rebase.
=> nimble/ll: Fix update chanmap in BIGInfo

nimble/host/src/ble_l2cap_sig.c
There was a typo which resulted in pulling up pointer size instead of request size.
=> nimble/host: Fix invalid pullup in L2CAP connection request

nimble/controller/src/ble_ll_iso_big.c
BIG handle has to be assigned before other checks that may fail as it's used to check if BIG is allocated. If not assigned properly, the BIG may not be freed in case of an error.
=> nimble/ll: Fix allocating BIG

nimble/host/mesh/src/cfg_cli.c
Fixes compilation error:
Error: repos/apache-mynewt-nimble/nimble/host/mesh/src/cfg_cli.c: In function 'mod_member_list_handle':
repos/apache-mynewt-nimble/nimble/host/mesh/src/cfg_cli.c:486:18: error: 'cid' may be used uninitialized [-Werror=maybe-uninitialized]
486 |             (vnd && param->cid != cid)) {
|             ~~~~~^~~~~~~~~~~~~~~~~~~~~
repos/apache-mynewt-nimble/nimble/host/mesh/src/cfg_cli.c:468:37:
note: 'cid' was declared here
468 |         uint16_t elem_addr, mod_id, cid;
|                                     ^~~
=> apps: bttester: fix compilation error

apps/bttester/src/btp_gatt.c
New variable that stores value handle of characterisic is introduced. It's needed to properly register predefined characteristics. Previously, two characteristics were using same variable to store value handle, so registering both of them resulted in overwriting handle of the former one
=> nimble: bttester: add variable to properly initialize characteristics

apps/bttester/syscfg.yml
BTTESTER_CONN_PARAM_UPDATE is leftover and is no longer used in code.
=> apps/bttester: Remove not used syscfg value

porting/nimble/src/nimble_port.c
`nimble_port_init()` needs to call ble_ll_init() when controller is enabled.
=> porting: add missing call to ble_ll_init

apps/bttester/src/btp_gatt.c
This characteristic is needed to pass tests that verify if IUT is able to respond with Insufficient Authorization error code to read, write requests from PTS.
=> apps: bttester: add characteristic to bttester database

nimble/controller/src/ble_ll_iso_big.c
ISO events should have 'fixed' flag set for scheduling, except for the 1st one, so they can preempt any other event.
=> nimble/ll: Fix ISO BIG events scheduling

nimble/controller/src/ble_ll_hci_vs.c
ble_ll_hci_vs.c module uses ARRAY_SIZE, defined in os/util.h.
=> controller: add missing os/util.h include

porting/npl/freertos/include/nimble/nimble_npl_os_log.h
=> porting: fix missing include for stdio

nimble/host/src/ble_eatt.c
Refactor some of the returns to
keep constant styling trough ble_eatt.c
=> nimble/eatt: Minor formatting fixes

nimble/host/src/ble_gap.c, nimble/include/nimble/ble.h
Devices can send anonymous address type during advertising.  Added support for this address type which is needed while Adding device to filter accept list
Core spec version 6.0, Vol 4 , Part E, section 7.8.16 lists Anonymous Address type as valid value for LE Add Device to Filter Accept List Command.  Current code doesn't consider this address type.
=> nimble/host: Add support for Anonymous address type

apps/bttester/src/btp_gap.c
Introduce setting filter policy when accept list is used.
Fix for improper loop initialization during advertising setup.
Those fixes are related to GAP/BROB/BCST/BV-05-C test failing.
=> apps/bttester: Filter policy setup & advertising data fix

apps/bttester/src/btp/btp_gatt.h, apps/bttester/src/btp_gatt.c
Add functionality to utilize BTP notify multiple command.
Previous notify handling via set_mult parses non-existent data.
=> apps: bttester: Implement notify / Remove set_mult

apps/bttester/src/btp/bttester.h, apps/bttester/src/btp_bap.c, apps/bttester/src/btp_core.c, apps/bttester/src/btp_gap.c, apps/bttester/src/btp_gatt.c, apps/bttester/src/btp_gatt_cl.c, apps/bttester/src/btp_l2cap.c, apps/bttester/src/btp_mesh.c, apps/bttester/src/btp_pacs.c, apps/bttester/src/bttester.c
Implement new way for reporting supported commands. Now only commands with registered handler will
be present in the queried response.
=> apps/bttester: Refactor reporting supported commands

apps/bttester/src/btp/btp_gap.h, apps/bttester/src/btp_gap.c
Get BTP event up to speed with autopts requirements.
Fill missing field in sync established event.
=> BTP Periodic Sync Transfer  & Sync established event refactor

nimble/host/test/src/ble_att_svr_test.c, nimble/host/test/src/ble_gatts_notify_test.c, nimble/host/test/src/ble_gatts_reg_test.c
This fixes:
- one obvious error where memcpy touches unspecified memory
- second is not really a bug buf false positive warning about uninitialized variables. Since it it only unit test there is no harm in initializing local variable to silence compiler
=> Trivial unit tests fixes

.github/workflows/compliance_check.yml
Replace apt-based clang-format install with pip to ensure consistency across environments.
Also update diff base to use merge-base and switch to clang-format-diff.py for more accurate formatting checks.
=> Force style check workflow to use pip-installed clang-format & proper merge-base

nimble/host/src/ble_att.c
Add a missing instance of ble_hs_unblock() when code returns due to failure
=> nimble/host: Add a missing instance of ble_hs_unblock()

.clang-format
Previous configuration produced weirdly formatted
results while dealing with long strings.
=> Disable string breaking in clang-format

.github/workflows/format_file_check.yml
Add `set +e` to the format_file_check.yml
to allow non-critical commands (e.g., git diff)  to fail gracefully.
This prevents early termination and enables
custom handling of command exit codes when needed.
=> Format file check - disable exit on failure in workflow shell

nimble/controller/src/ble_ll_conn.c
In [ble_ll_conn.c](https://github.com/apache/mynewt-nimble/blob/master/nimble/controller/src/ble_ll_conn.c#L1294), the data pointer in the mbuf of outgoing empty packets is set to an invalid value (pointing right after `struct ble_ll_empty_pdu` on the stack). The invalid pointer is then dereferenced to check if the outgoing packet is a terminate_ind:
```c
conn_tx_pdu:
if (connsm->flags.empty_pdu_txd) {
/*
* This looks strange, but we dont use the data pointer in the mbuf
* when we have an empty pdu.
*/
m = (struct os_mbuf *)&empty_pdu;
m->om_data = (uint8_t *)&empty_pdu;
m->om_data += BLE_MBUF_MEMBLOCK_OVERHEAD;
ble_hdr = &empty_pdu.ble_hdr;
ble_hdr->txinfo.num_data_pkt = 0;
ble_hdr->txinfo.offset = 0;
ble_hdr->txinfo.pyld_len = 0;
}
//...
if ((connsm->flags.terminate_ind_rxd) || …
```
=> nimble/ll: Avoid dereferencing an invalid pointer

.github/workflows/compliance_check.yml
This update adds a label-based conditional to the compliance_check.yml GitHub Actions workflow. If a pull request includes the label `skip-style-check`, the style check step will be skipped.
This allows maintainers to bypass formatting validation in exceptional cases, such as bulk updates or style-irrelevant changes.
=> Skip style-check workflow if label is present

nimble/controller/src/ble_ll_sched.c
This update adjusts the scheduling policy for periodic advertising to ensure it does not preempt BIG events. This ensures stability and performance of audio.
=> nimble/ll: Prevent BIG event preemption by periodic advertising

nimble/transport/common/hci_h4/src/hci_h4.c
If received HCI event is too big to handle just return error and stop parsing instead of overwriting data in memeory.
=> nimble/transport: Skip H4 event parsing if received event is too big

nimble/controller/syscfg.yml
Add condition for enabling subrating for controller based on value set in host configuration.
=> controller: Add subrating condition in syscfg

apps/bttester/src/btp_gap.c
Previous assignment was wrong due to device not being connected while periodic sync and periodic transfer events were occurring.
Now address is assigned from actual information stored in event structure.
=> nimble/btp: Fix address assignment in padv operations

.github/workflows/compliance_check.yml
This workflow checks all commits between the current branch and upstream/master. It enforces subject length, colon usage in the subject line, and body line length. This helps maintain consistency and readability in the project's history.
=> ci: Add GitHub Action to validate commit message style

nimble/controller/include/controller/ble_ll_ctrl.h, nimble/controller/src/ble_ll_conn.c, nimble/controller/src/ble_ll_conn_hci.c, nimble/controller/src/ble_ll_ctrl.c
This was used in the past, but no longer needed.
=> nimble/ll: Remove unused parameter

nimble/include/nimble/hci_common.h, nimble/syscfg.yml
This allows to configure stack as Bluetooth Core 6.1.
=> nimble: Add option to select Core 6.1

nimble/host/src/ble_l2cap_sig.c
Transaction ID was used instead of procedure opcode which resulted in not calling application callback on second and subsequent rejection.
=> nimble/host: Fix typo in ble_l2cap_sig_rx_reject

apps/bttester/src/btp/btp_bap.h
Bring BAP commands and events up to date with their corresponding counterparts in Auto-PTS.
=> nimble/btp: Implement missing BAP layer commands & events

nimble/host/src/ble_gap.c, nimble/host/src/ble_hs.c, nimble/transport/src/monitor.c
If no timeout is required we should use BLE_NPL_TIME_FOREVER when locking.
=> nimble: Use BLE_NPL_TIME_FOREVER for ble_npl_mutex_pend timeout

nimble/drivers/dialog_cmac/src/ble_phy.c
The assert was originally added for debugging purposes a long time ago. It has been reported to cause issues in DTM, so it is now removed to prevent further problems.
=> nimble/phy/cmac: Remove redundant assert

porting/npl/nuttx/src/os_callout.c
porting/npl/nuttx/src/os_callout.c:125:24: error: comparison between pointer and integer [-Werror]
125 |     return (c->c_timer != NULL);
|                        ^~
cc1: all warnings being treated as errors
=> porting/npl/nuttx: fix compile error
